#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Activate_Ability2ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Activate_Ability2ActionTraits.Activate_Ability2ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UActivate_Ability2ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Activate_Ability2ActionTraits_C">();
	}
	static class UActivate_Ability2ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivate_Ability2ActionTraits_C>();
	}
};
static_assert(alignof(UActivate_Ability2ActionTraits_C) == 0x000008, "Wrong alignment on UActivate_Ability2ActionTraits_C");
static_assert(sizeof(UActivate_Ability2ActionTraits_C) == 0x000040, "Wrong size on UActivate_Ability2ActionTraits_C");

}

