#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Activate_MeleeActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Activate_MeleeActionTraits.Activate_MeleeActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UActivate_MeleeActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Activate_MeleeActionTraits_C">();
	}
	static class UActivate_MeleeActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActivate_MeleeActionTraits_C>();
	}
};
static_assert(alignof(UActivate_MeleeActionTraits_C) == 0x000008, "Wrong alignment on UActivate_MeleeActionTraits_C");
static_assert(sizeof(UActivate_MeleeActionTraits_C) == 0x000040, "Wrong size on UActivate_MeleeActionTraits_C");

}

