#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ActionTraitsManager

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ActionTraitsManager.ActionTraitsManager_C
// 0x0000 (0x0090 - 0x0090)
class UActionTraitsManager_C final : public UActionTraitsManager
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ActionTraitsManager_C">();
	}
	static class UActionTraitsManager_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UActionTraitsManager_C>();
	}
};
static_assert(alignof(UActionTraitsManager_C) == 0x000008, "Wrong alignment on UActionTraitsManager_C");
static_assert(sizeof(UActionTraitsManager_C) == 0x000090, "Wrong size on UActionTraitsManager_C");

}

