#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AllChatActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AllChatActionTraits.AllChatActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UAllChatActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AllChatActionTraits_C">();
	}
	static class UAllChatActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAllChatActionTraits_C>();
	}
};
static_assert(alignof(UAllChatActionTraits_C) == 0x000008, "Wrong alignment on UAllChatActionTraits_C");
static_assert(sizeof(UAllChatActionTraits_C) == 0x000040, "Wrong size on UAllChatActionTraits_C");

}

