#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AresMinimapWidget

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "ShooterGame_structs.hpp"
#include "ShooterGame_classes.hpp"
#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AresMinimapWidget.AresMinimapWidget_C
// 0x00C8 (0x0368 - 0x02A0)
class UAresMinimapWidget_C : public UAresMinimapWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02A0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	EAresMinimapLayer                             MinimapLayer;                                      // 0x02A8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAresMinimapPositionSpace                     Minimap_Position_Space;                            // 0x02A9(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	EAresMinimapRotationSpace                     Minimap_Rotation_Space;                            // 0x02AA(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAresMinimapSizeSpace                         Minimap_Size_Space;                                // 0x02AB(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	struct FVector                                Minimap_Position;                                  // 0x02AC(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Minimap_Rotation;                                  // 0x02B8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Minimap_Size;                                      // 0x02BC(0x000C)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FSlateBrush                            Brush;                                             // 0x02C8(0x0090)(Edit, BlueprintVisible, BlueprintReadOnly)
	struct FVector2D                              Alignment;                                         // 0x0358(0x0008)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Draw_Off_Map;                                      // 0x0360(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_AresMinimapWidget(int32 EntryPoint);
	void Construct();
	void PreConstruct(bool IsDesignTime);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AresMinimapWidget_C">();
	}
	static class UAresMinimapWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAresMinimapWidget_C>();
	}
};
static_assert(alignof(UAresMinimapWidget_C) == 0x000008, "Wrong alignment on UAresMinimapWidget_C");
static_assert(sizeof(UAresMinimapWidget_C) == 0x000368, "Wrong size on UAresMinimapWidget_C");
static_assert(offsetof(UAresMinimapWidget_C, UberGraphFrame) == 0x0002A0, "Member 'UAresMinimapWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, MinimapLayer) == 0x0002A8, "Member 'UAresMinimapWidget_C::MinimapLayer' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Minimap_Position_Space) == 0x0002A9, "Member 'UAresMinimapWidget_C::Minimap_Position_Space' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Minimap_Rotation_Space) == 0x0002AA, "Member 'UAresMinimapWidget_C::Minimap_Rotation_Space' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Minimap_Size_Space) == 0x0002AB, "Member 'UAresMinimapWidget_C::Minimap_Size_Space' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Minimap_Position) == 0x0002AC, "Member 'UAresMinimapWidget_C::Minimap_Position' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Minimap_Rotation) == 0x0002B8, "Member 'UAresMinimapWidget_C::Minimap_Rotation' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Minimap_Size) == 0x0002BC, "Member 'UAresMinimapWidget_C::Minimap_Size' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Brush) == 0x0002C8, "Member 'UAresMinimapWidget_C::Brush' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Alignment) == 0x000358, "Member 'UAresMinimapWidget_C::Alignment' has a wrong offset!");
static_assert(offsetof(UAresMinimapWidget_C, Draw_Off_Map) == 0x000360, "Member 'UAresMinimapWidget_C::Draw_Off_Map' has a wrong offset!");

}

