#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BaseAudioComponent

#include "Basic.hpp"

#include "BaseAudioComponent_classes.hpp"
#include "BaseAudioComponent_parameters.hpp"


namespace SDK
{

// Function BaseAudioComponent.BaseAudioComponent_C.ExecuteUbergraph_BaseAudioComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBaseAudioComponent_C::ExecuteUbergraph_BaseAudioComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_BaseAudioComponent");

	Params::BaseAudioComponent_C_ExecuteUbergraph_BaseAudioComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BaseAudioComponent.BaseAudioComponent_C.AudioTick
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTime                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBaseAudioComponent_C::AudioTick(float DeltaTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AudioTick");

	Params::BaseAudioComponent_C_AudioTick Parms{};

	Parms.DeltaTime = DeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BaseAudioComponent.BaseAudioComponent_C.GetComponentDebugString
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           DebugString                                            (Parm, OutParm, ZeroConstructor, HasGetValueTypeHash)

void UBaseAudioComponent_C::GetComponentDebugString(class FString* DebugString)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetComponentDebugString");

	Params::BaseAudioComponent_C_GetComponentDebugString Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (DebugString != nullptr)
		*DebugString = std::move(Parms.DebugString);
}

}

