#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPAresSettingsManager_Mobile

#include "Basic.hpp"

#include "BPAresSettingsManager_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BPAresSettingsManager_Mobile.BPAresSettingsManager_Mobile_C
// 0x0000 (0x0328 - 0x0328)
class UBPAresSettingsManager_Mobile_C final : public UBPAresSettingsManager_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BPAresSettingsManager_Mobile_C">();
	}
	static class UBPAresSettingsManager_Mobile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBPAresSettingsManager_Mobile_C>();
	}
};
static_assert(alignof(UBPAresSettingsManager_Mobile_C) == 0x000008, "Wrong alignment on UBPAresSettingsManager_Mobile_C");
static_assert(sizeof(UBPAresSettingsManager_Mobile_C) == 0x000328, "Wrong size on UBPAresSettingsManager_Mobile_C");

}

