#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BuildNumberDisplay

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass BuildNumberDisplay.BuildNumberDisplay_C
// 0x0010 (0x02A8 - 0x0298)
class UBuildNumberDisplay_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UTextBlock*                             BuildNumber;                                       // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BuildNumberDisplay(int32 EntryPoint);
	void PreConstruct(bool IsDesignTime);
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"BuildNumberDisplay_C">();
	}
	static class UBuildNumberDisplay_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UBuildNumberDisplay_C>();
	}
};
static_assert(alignof(UBuildNumberDisplay_C) == 0x000008, "Wrong alignment on UBuildNumberDisplay_C");
static_assert(sizeof(UBuildNumberDisplay_C) == 0x0002A8, "Wrong size on UBuildNumberDisplay_C");
static_assert(offsetof(UBuildNumberDisplay_C, UberGraphFrame) == 0x000298, "Member 'UBuildNumberDisplay_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UBuildNumberDisplay_C, BuildNumber) == 0x0002A0, "Member 'UBuildNumberDisplay_C::BuildNumber' has a wrong offset!");

}

