#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ClientNavRightActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ClientNavRightActionTraits.ClientNavRightActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UClientNavRightActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ClientNavRightActionTraits_C">();
	}
	static class UClientNavRightActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UClientNavRightActionTraits_C>();
	}
};
static_assert(alignof(UClientNavRightActionTraits_C) == 0x000008, "Wrong alignment on UClientNavRightActionTraits_C");
static_assert(sizeof(UClientNavRightActionTraits_C) == 0x000040, "Wrong size on UClientNavRightActionTraits_C");

}

