#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommMenuOption2ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommMenuOption2ActionTraits.CommMenuOption2ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UCommMenuOption2ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CommMenuOption2ActionTraits_C">();
	}
	static class UCommMenuOption2ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommMenuOption2ActionTraits_C>();
	}
};
static_assert(alignof(UCommMenuOption2ActionTraits_C) == 0x000008, "Wrong alignment on UCommMenuOption2ActionTraits_C");
static_assert(sizeof(UCommMenuOption2ActionTraits_C) == 0x000040, "Wrong size on UCommMenuOption2ActionTraits_C");

}

