#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommMenuOption1ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommMenuOption1ActionTraits.CommMenuOption1ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UCommMenuOption1ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CommMenuOption1ActionTraits_C">();
	}
	static class UCommMenuOption1ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommMenuOption1ActionTraits_C>();
	}
};
static_assert(alignof(UCommMenuOption1ActionTraits_C) == 0x000008, "Wrong alignment on UCommMenuOption1ActionTraits_C");
static_assert(sizeof(UCommMenuOption1ActionTraits_C) == 0x000040, "Wrong size on UCommMenuOption1ActionTraits_C");

}

