#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommMenuOption4ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommMenuOption4ActionTraits.CommMenuOption4ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UCommMenuOption4ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CommMenuOption4ActionTraits_C">();
	}
	static class UCommMenuOption4ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommMenuOption4ActionTraits_C>();
	}
};
static_assert(alignof(UCommMenuOption4ActionTraits_C) == 0x000008, "Wrong alignment on UCommMenuOption4ActionTraits_C");
static_assert(sizeof(UCommMenuOption4ActionTraits_C) == 0x000040, "Wrong size on UCommMenuOption4ActionTraits_C");

}

