#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommMenuOption7ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommMenuOption7ActionTraits.CommMenuOption7ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UCommMenuOption7ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CommMenuOption7ActionTraits_C">();
	}
	static class UCommMenuOption7ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommMenuOption7ActionTraits_C>();
	}
};
static_assert(alignof(UCommMenuOption7ActionTraits_C) == 0x000008, "Wrong alignment on UCommMenuOption7ActionTraits_C");
static_assert(sizeof(UCommMenuOption7ActionTraits_C) == 0x000040, "Wrong size on UCommMenuOption7ActionTraits_C");

}

