#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CommMenuOption0ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CommMenuOption0ActionTraits.CommMenuOption0ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UCommMenuOption0ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CommMenuOption0ActionTraits_C">();
	}
	static class UCommMenuOption0ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCommMenuOption0ActionTraits_C>();
	}
};
static_assert(alignof(UCommMenuOption0ActionTraits_C) == 0x000008, "Wrong alignment on UCommMenuOption0ActionTraits_C");
static_assert(sizeof(UCommMenuOption0ActionTraits_C) == 0x000040, "Wrong size on UCommMenuOption0ActionTraits_C");

}

