#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ConfirmationModal

#include "Basic.hpp"

#include "ConfirmationModal_classes.hpp"
#include "ConfirmationModal_parameters.hpp"


namespace SDK
{

// Function ConfirmationModal.ConfirmationModal_C.ExecuteUbergraph_ConfirmationModal
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfirmationModal_C::ExecuteUbergraph_ConfirmationModal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_ConfirmationModal");

	Params::ConfirmationModal_C_ExecuteUbergraph_ConfirmationModal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.BndEvt__RightButton_K2Node_ComponentBoundEvent_2_Clicked__DelegateSignature
// (BlueprintEvent)

void UConfirmationModal_C::BndEvt__RightButton_K2Node_ComponentBoundEvent_2_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__RightButton_K2Node_ComponentBoundEvent_2_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfirmationModal.ConfirmationModal_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UConfirmationModal_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfirmationModal.ConfirmationModal_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UConfirmationModal_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfirmationModal.ConfirmationModal_C.BndEvt__CancelButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature
// (BlueprintEvent)

void UConfirmationModal_C::BndEvt__CancelButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__CancelButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfirmationModal.ConfirmationModal_C.BndEvt__ConfirmButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature
// (BlueprintEvent)

void UConfirmationModal_C::BndEvt__ConfirmButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__ConfirmButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfirmationModal.ConfirmationModal_C.OnSynchronizeProperties
// (Event, Public, BlueprintEvent)

void UConfirmationModal_C::OnSynchronizeProperties()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnSynchronizeProperties");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfirmationModal.ConfirmationModal_C.Launch
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIsLaunched                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConfirmationModal_C::Launch(bool InIsLaunched)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Launch");

	Params::ConfirmationModal_C_Launch Parms{};

	Parms.InIsLaunched = InIsLaunched;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.Get_SharedButtonCancel_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UConfirmationModal_C::Get_SharedButtonCancel_Visibility()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Get_SharedButtonCancel_Visibility");

	Params::ConfirmationModal_C_Get_SharedButtonCancel_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConfirmationModal.ConfirmationModal_C.SetMessageText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UConfirmationModal_C::SetMessageText(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetMessageText");

	Params::ConfirmationModal_C_SetMessageText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.SetTitleText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UConfirmationModal_C::SetTitleText(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetTitleText");

	Params::ConfirmationModal_C_SetTitleText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.SetConfirmationButtonText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UConfirmationModal_C::SetConfirmationButtonText(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetConfirmationButtonText");

	Params::ConfirmationModal_C_SetConfirmationButtonText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.SetCancelButtonText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UConfirmationModal_C::SetCancelButtonText(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetCancelButtonText");

	Params::ConfirmationModal_C_SetCancelButtonText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.SetShowCustomBody
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ShowCustomBody                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UConfirmationModal_C::SetShowCustomBody(bool ShowCustomBody)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetShowCustomBody");

	Params::ConfirmationModal_C_SetShowCustomBody Parms{};

	Parms.ShowCustomBody = ShowCustomBody;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.SetCancelButtonVisible
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfirmationModal_C::SetCancelButtonVisible(ESlateVisibility Visible)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetCancelButtonVisible");

	Params::ConfirmationModal_C_SetCancelButtonVisible Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.SetMiddleButtonVisible
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfirmationModal_C::SetMiddleButtonVisible(ESlateVisibility Visible)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetMiddleButtonVisible");

	Params::ConfirmationModal_C_SetMiddleButtonVisible Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.Get_SharedButtonMiddle_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UConfirmationModal_C::Get_SharedButtonMiddle_Visibility()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Get_SharedButtonMiddle_Visibility");

	Params::ConfirmationModal_C_Get_SharedButtonMiddle_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConfirmationModal.ConfirmationModal_C.SetButtonColors
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UConfirmationModal_C::SetButtonColors()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetButtonColors");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ConfirmationModal.ConfirmationModal_C.GetIndividualButtonColor
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// EButtonColors                           ButtonColorEnum                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FSharedButtonStyle               ReturnedColor                                          (Parm, OutParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfirmationModal_C::GetIndividualButtonColor(EButtonColors ButtonColorEnum, struct FSharedButtonStyle* ReturnedColor)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetIndividualButtonColor");

	Params::ConfirmationModal_C_GetIndividualButtonColor Parms{};

	Parms.ButtonColorEnum = ButtonColorEnum;

	UObject::ProcessEvent(Func, &Parms);

	if (ReturnedColor != nullptr)
		*ReturnedColor = std::move(Parms.ReturnedColor);
}


// Function ConfirmationModal.ConfirmationModal_C.SetMiddleButtonText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             Text                                                   (BlueprintVisible, BlueprintReadOnly, Parm)

void UConfirmationModal_C::SetMiddleButtonText(const class FText& Text)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetMiddleButtonText");

	Params::ConfirmationModal_C_SetMiddleButtonText Parms{};

	Parms.Text = std::move(Text);

	UObject::ProcessEvent(Func, &Parms);
}


// Function ConfirmationModal.ConfirmationModal_C.Get_SharedButtonClose_Visibility
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// ESlateVisibility                        ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

ESlateVisibility UConfirmationModal_C::Get_SharedButtonClose_Visibility()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Get_SharedButtonClose_Visibility");

	Params::ConfirmationModal_C_Get_SharedButtonClose_Visibility Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function ConfirmationModal.ConfirmationModal_C.SetCloseButtonVisible
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// ESlateVisibility                        Visible                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UConfirmationModal_C::SetCloseButtonVisible(ESlateVisibility Visible)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetCloseButtonVisible");

	Params::ConfirmationModal_C_SetCloseButtonVisible Parms{};

	Parms.Visible = Visible;

	UObject::ProcessEvent(Func, &Parms);
}

}

