#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: CrouchActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass CrouchActionTraits.CrouchActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UCrouchActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"CrouchActionTraits_C">();
	}
	static class UCrouchActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCrouchActionTraits_C>();
	}
};
static_assert(alignof(UCrouchActionTraits_C) == 0x000008, "Wrong alignment on UCrouchActionTraits_C");
static_assert(sizeof(UCrouchActionTraits_C) == 0x000040, "Wrong size on UCrouchActionTraits_C");

}

