#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DirectConnectWidget

#include "Basic.hpp"

#include "ShooterGame_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function DirectConnectWidget.DirectConnectWidget_C.ExecuteUbergraph_DirectConnectWidget
// 0x02E8 (0x02E8 - 0x0000)
struct DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_ComponentBoundEvent_Text_1;                 // 0x0008(0x0018)(ConstParm)
	class FString                                 CallFunc_GetSelectedOption_ReturnValue;            // 0x0020(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x0030(0x0018)(ConstParm)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0048(0x0018)()
	class FText                                   CallFunc_GetText_ReturnValue_1;                    // 0x0060(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x0088(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Conv_StringToInt_ReturnValue;             // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_9C[0x4];                                       // 0x009C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue_2;                    // 0x00A0(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_2;          // 0x00B8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_3;                    // 0x00C8(0x0018)()
	int32                                         CallFunc_Len_ReturnValue;                          // 0x00E0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_E4[0x4];                                       // 0x00E4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_3;          // 0x00E8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x00F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_F9[0x3];                                       // 0x00F9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Len_ReturnValue_1;                        // 0x00FC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class URSOManager*                            CallFunc_GetRSOManager_ReturnValue;                // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FRSOUserInfo                           CallFunc_GetRSOUserInfo_ReturnValue;               // 0x0110(0x0040)()
	bool                                          CallFunc_BooleanAND_ReturnValue;                   // 0x0150(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_151[0x7];                                      // 0x0151(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue;    // 0x0158(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USharedSecondaryButtonText_C*           K2Node_ComponentBoundEvent_TextButton;             // 0x0160(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_UsingTouchInput_ReturnValue;              // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_UsingTouchInput_ReturnValue_1;            // 0x0169(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_16A[0x6];                                      // 0x016A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_GetText_ReturnValue_4;                    // 0x0170(0x0018)()
	bool                                          CallFunc_UsingTouchInput_ReturnValue_2;            // 0x0188(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_189[0x7];                                      // 0x0189(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_4;          // 0x0190(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue_2;                        // 0x01A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1A4[0x4];                                      // 0x01A4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDirectConnectSettings                 CallFunc_GetCachedDirectConnectSettings_Settings;  // 0x01A8(0x0050)()
	bool                                          CallFunc_GetCachedDirectConnectSettings_ReturnValue; // 0x01F8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_2;             // 0x01F9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1FA[0x6];                                      // 0x01FA(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	struct FDirectConnectSettings                 CallFunc_GetConnectSettings_Settings;              // 0x0200(0x0050)()
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem_1;         // 0x0250(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType_1;        // 0x0260(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_261[0x7];                                      // 0x0261(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_ComponentBoundEvent_SelectedItem;           // 0x0268(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   K2Node_ComponentBoundEvent_SelectionType;          // 0x0278(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_279[0x7];                                      // 0x0279(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FConnectToServerDetails                K2Node_MakeStruct_ConnectToServerDetails;          // 0x0280(0x0058)()
	class FString                                 CallFunc_GetSelectedOption_ReturnValue_1;          // 0x02D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
};
static_assert(alignof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget) == 0x000008, "Wrong alignment on DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget");
static_assert(sizeof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget) == 0x0002E8, "Wrong size on DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, EntryPoint) == 0x000000, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::EntryPoint' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_ComponentBoundEvent_Text_1) == 0x000008, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_ComponentBoundEvent_Text_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetSelectedOption_ReturnValue) == 0x000020, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetSelectedOption_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_ComponentBoundEvent_Text) == 0x000030, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetText_ReturnValue) == 0x000048, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetText_ReturnValue_1) == 0x000060, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Conv_TextToString_ReturnValue) == 0x000078, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Conv_TextToString_ReturnValue_1) == 0x000088, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Conv_StringToInt_ReturnValue) == 0x000098, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Conv_StringToInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetText_ReturnValue_2) == 0x0000A0, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Conv_TextToString_ReturnValue_2) == 0x0000B8, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Conv_TextToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetText_ReturnValue_3) == 0x0000C8, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetText_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Len_ReturnValue) == 0x0000E0, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Conv_TextToString_ReturnValue_3) == 0x0000E8, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Conv_TextToString_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Greater_IntInt_ReturnValue) == 0x0000F8, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Len_ReturnValue_1) == 0x0000FC, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Len_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetRSOManager_ReturnValue) == 0x000100, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetRSOManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Greater_IntInt_ReturnValue_1) == 0x000108, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetRSOUserInfo_ReturnValue) == 0x000110, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetRSOUserInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_BooleanAND_ReturnValue) == 0x000150, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_BooleanAND_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetAresClientGameInstance_ReturnValue) == 0x000158, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetAresClientGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_ComponentBoundEvent_TextButton) == 0x000160, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_ComponentBoundEvent_TextButton' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_UsingTouchInput_ReturnValue) == 0x000168, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_UsingTouchInput_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_UsingTouchInput_ReturnValue_1) == 0x000169, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_UsingTouchInput_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetText_ReturnValue_4) == 0x000170, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetText_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_UsingTouchInput_ReturnValue_2) == 0x000188, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_UsingTouchInput_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Conv_TextToString_ReturnValue_4) == 0x000190, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Conv_TextToString_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Len_ReturnValue_2) == 0x0001A0, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Len_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetCachedDirectConnectSettings_Settings) == 0x0001A8, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetCachedDirectConnectSettings_Settings' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetCachedDirectConnectSettings_ReturnValue) == 0x0001F8, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetCachedDirectConnectSettings_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_Greater_IntInt_ReturnValue_2) == 0x0001F9, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_Greater_IntInt_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetConnectSettings_Settings) == 0x000200, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetConnectSettings_Settings' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_ComponentBoundEvent_SelectedItem_1) == 0x000250, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_ComponentBoundEvent_SelectedItem_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_ComponentBoundEvent_SelectionType_1) == 0x000260, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_ComponentBoundEvent_SelectionType_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_ComponentBoundEvent_SelectedItem) == 0x000268, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_ComponentBoundEvent_SelectedItem' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_ComponentBoundEvent_SelectionType) == 0x000278, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_ComponentBoundEvent_SelectionType' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, K2Node_MakeStruct_ConnectToServerDetails) == 0x000280, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::K2Node_MakeStruct_ConnectToServerDetails' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget, CallFunc_GetSelectedOption_ReturnValue_1) == 0x0002D8, "Member 'DirectConnectWidget_C_ExecuteUbergraph_DirectConnectWidget::CallFunc_GetSelectedOption_ReturnValue_1' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature");
static_assert(sizeof(DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature) == 0x000018, "Wrong size on DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature");
static_assert(offsetof(DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature, SelectedItem) == 0x000000, "Member 'DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature, SelectionType) == 0x000010, "Member 'DirectConnectWidget_C_BndEvt__TeamBDropdown_K2Node_ComponentBoundEvent_2_OnSelectionChangedEvent__DelegateSignature::SelectionType' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature final
{
public:
	class FString                                 SelectedItem;                                      // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	ESelectInfo                                   SelectionType;                                     // 0x0010(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature");
static_assert(sizeof(DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature) == 0x000018, "Wrong size on DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature");
static_assert(offsetof(DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature, SelectedItem) == 0x000000, "Member 'DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature::SelectedItem' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature, SelectionType) == 0x000010, "Member 'DirectConnectWidget_C_BndEvt__TeamADropdown_K2Node_ComponentBoundEvent_0_OnSelectionChangedEvent__DelegateSignature::SelectionType' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct DirectConnectWidget_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature final
{
public:
	class USharedSecondaryButtonText_C*           TextButton;                                        // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(DirectConnectWidget_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature) == 0x000008, "Wrong alignment on DirectConnectWidget_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature");
static_assert(sizeof(DirectConnectWidget_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature) == 0x000008, "Wrong size on DirectConnectWidget_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature");
static_assert(offsetof(DirectConnectWidget_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature, TextButton) == 0x000000, "Member 'DirectConnectWidget_C_BndEvt__Button_K2Node_ComponentBoundEvent_1_OnPressed__DelegateSignature::TextButton' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct DirectConnectWidget_C_BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(DirectConnectWidget_C_BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on DirectConnectWidget_C_BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature");
static_assert(sizeof(DirectConnectWidget_C_BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature) == 0x000018, "Wrong size on DirectConnectWidget_C_BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature");
static_assert(offsetof(DirectConnectWidget_C_BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature, Text) == 0x000000, "Member 'DirectConnectWidget_C_BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature::Text' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct DirectConnectWidget_C_BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(DirectConnectWidget_C_BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on DirectConnectWidget_C_BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature");
static_assert(sizeof(DirectConnectWidget_C_BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature) == 0x000018, "Wrong size on DirectConnectWidget_C_BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature");
static_assert(offsetof(DirectConnectWidget_C_BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature, Text) == 0x000000, "Member 'DirectConnectWidget_C_BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature::Text' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.PopulateCachedSettings
// 0x0098 (0x0098 - 0x0000)
struct DirectConnectWidget_C_PopulateCachedSettings final
{
public:
	struct FDirectConnectSettings                 Settings;                                          // 0x0000(0x0050)(BlueprintVisible, BlueprintReadOnly, Parm)
	class FText                                   CallFunc_Conv_StringToText_ReturnValue;            // 0x0050(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_1;          // 0x0068(0x0018)()
	class FText                                   CallFunc_Conv_StringToText_ReturnValue_2;          // 0x0080(0x0018)()
};
static_assert(alignof(DirectConnectWidget_C_PopulateCachedSettings) == 0x000008, "Wrong alignment on DirectConnectWidget_C_PopulateCachedSettings");
static_assert(sizeof(DirectConnectWidget_C_PopulateCachedSettings) == 0x000098, "Wrong size on DirectConnectWidget_C_PopulateCachedSettings");
static_assert(offsetof(DirectConnectWidget_C_PopulateCachedSettings, Settings) == 0x000000, "Member 'DirectConnectWidget_C_PopulateCachedSettings::Settings' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_PopulateCachedSettings, CallFunc_Conv_StringToText_ReturnValue) == 0x000050, "Member 'DirectConnectWidget_C_PopulateCachedSettings::CallFunc_Conv_StringToText_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_PopulateCachedSettings, CallFunc_Conv_StringToText_ReturnValue_1) == 0x000068, "Member 'DirectConnectWidget_C_PopulateCachedSettings::CallFunc_Conv_StringToText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_PopulateCachedSettings, CallFunc_Conv_StringToText_ReturnValue_2) == 0x000080, "Member 'DirectConnectWidget_C_PopulateCachedSettings::CallFunc_Conv_StringToText_ReturnValue_2' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.GetConnectSettings
// 0x0138 (0x0138 - 0x0000)
struct DirectConnectWidget_C_GetConnectSettings final
{
public:
	struct FDirectConnectSettings                 Settings;                                          // 0x0000(0x0050)(Parm, OutParm)
	class FString                                 CallFunc_GetSelectedOption_ReturnValue;            // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_GetSelectedOption_ReturnValue_1;          // 0x0060(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0070(0x0018)()
	class FText                                   CallFunc_GetText_ReturnValue_1;                    // 0x0088(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00A0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_1;          // 0x00B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue_2;                    // 0x00C0(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue_2;          // 0x00D8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FDirectConnectSettings                 K2Node_MakeStruct_DirectConnectSettings;           // 0x00E8(0x0050)()
};
static_assert(alignof(DirectConnectWidget_C_GetConnectSettings) == 0x000008, "Wrong alignment on DirectConnectWidget_C_GetConnectSettings");
static_assert(sizeof(DirectConnectWidget_C_GetConnectSettings) == 0x000138, "Wrong size on DirectConnectWidget_C_GetConnectSettings");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, Settings) == 0x000000, "Member 'DirectConnectWidget_C_GetConnectSettings::Settings' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_GetSelectedOption_ReturnValue) == 0x000050, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_GetSelectedOption_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_GetSelectedOption_ReturnValue_1) == 0x000060, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_GetSelectedOption_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_GetText_ReturnValue) == 0x000070, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_GetText_ReturnValue_1) == 0x000088, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_GetText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_Conv_TextToString_ReturnValue) == 0x0000A0, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_Conv_TextToString_ReturnValue_1) == 0x0000B0, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_Conv_TextToString_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_GetText_ReturnValue_2) == 0x0000C0, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_GetText_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, CallFunc_Conv_TextToString_ReturnValue_2) == 0x0000D8, "Member 'DirectConnectWidget_C_GetConnectSettings::CallFunc_Conv_TextToString_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_GetConnectSettings, K2Node_MakeStruct_DirectConnectSettings) == 0x0000E8, "Member 'DirectConnectWidget_C_GetConnectSettings::K2Node_MakeStruct_DirectConnectSettings' has a wrong offset!");

// Function DirectConnectWidget.DirectConnectWidget_C.SetGUID
// 0x0028 (0x0028 - 0x0000)
struct DirectConnectWidget_C_SetGUID final
{
public:
	class FString                                 Team_0;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	class FString                                 Player;                                            // 0x0010(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchString_CmpSuccess;                    // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchString_CmpSuccess_1;                  // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchString_CmpSuccess_2;                  // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_SwitchString_CmpSuccess_3;                  // 0x0023(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(DirectConnectWidget_C_SetGUID) == 0x000008, "Wrong alignment on DirectConnectWidget_C_SetGUID");
static_assert(sizeof(DirectConnectWidget_C_SetGUID) == 0x000028, "Wrong size on DirectConnectWidget_C_SetGUID");
static_assert(offsetof(DirectConnectWidget_C_SetGUID, Team_0) == 0x000000, "Member 'DirectConnectWidget_C_SetGUID::Team_0' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_SetGUID, Player) == 0x000010, "Member 'DirectConnectWidget_C_SetGUID::Player' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_SetGUID, K2Node_SwitchString_CmpSuccess) == 0x000020, "Member 'DirectConnectWidget_C_SetGUID::K2Node_SwitchString_CmpSuccess' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_SetGUID, K2Node_SwitchString_CmpSuccess_1) == 0x000021, "Member 'DirectConnectWidget_C_SetGUID::K2Node_SwitchString_CmpSuccess_1' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_SetGUID, K2Node_SwitchString_CmpSuccess_2) == 0x000022, "Member 'DirectConnectWidget_C_SetGUID::K2Node_SwitchString_CmpSuccess_2' has a wrong offset!");
static_assert(offsetof(DirectConnectWidget_C_SetGUID, K2Node_SwitchString_CmpSuccess_3) == 0x000023, "Member 'DirectConnectWidget_C_SetGUID::K2Node_SwitchString_CmpSuccess_3' has a wrong offset!");

}

