#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DPIScalingRules

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass DPIScalingRules.DPIScalingRules_C
// 0x0000 (0x0148 - 0x0148)
class UDPIScalingRules_C final : public UAresDPICustomScalingRule
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"DPIScalingRules_C">();
	}
	static class UDPIScalingRules_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDPIScalingRules_C>();
	}
};
static_assert(alignof(UDPIScalingRules_C) == 0x000008, "Wrong alignment on UDPIScalingRules_C");
static_assert(sizeof(UDPIScalingRules_C) == 0x000148, "Wrong size on UDPIScalingRules_C");

}

