#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: EjectableBounceFxc

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_structs.hpp"
#include "ShooterGame_classes.hpp"
#include "AkAudio_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass EjectableBounceFxc.EjectableBounceFxc_C
// 0x0050 (0x0530 - 0x04E0)
class AEjectableBounceFxc_C final : public AEffectContainer
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x04E8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class UAresAudioComponent*                    ReusableAudioComponent;                            // 0x04F0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          BounceAudioEvent;                                  // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EAresSurfaceType                              BounceSurfaceType;                                 // 0x0500(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_501[0x3];                                      // 0x0501(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         NumBounces;                                        // 0x0504(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         BounceSpeed;                                       // 0x0508(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_50C[0x4];                                      // 0x050C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AAresEjectable*                         Ejectable;                                         // 0x0510(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FString                                 WWisePerspective;                                  // 0x0518(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_EjectableBounceFxc(int32 EntryPoint);
	void StopEffect(EStopEffectType StopEffectType);
	void StartEffect(class AActor* Target, class UObject* Context, float StartTime, bool FirstPerson);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"EjectableBounceFxc_C">();
	}
	static class AEjectableBounceFxc_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AEjectableBounceFxc_C>();
	}
};
static_assert(alignof(AEjectableBounceFxc_C) == 0x000010, "Wrong alignment on AEjectableBounceFxc_C");
static_assert(sizeof(AEjectableBounceFxc_C) == 0x000530, "Wrong size on AEjectableBounceFxc_C");
static_assert(offsetof(AEjectableBounceFxc_C, UberGraphFrame) == 0x0004E0, "Member 'AEjectableBounceFxc_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, DefaultSceneRoot) == 0x0004E8, "Member 'AEjectableBounceFxc_C::DefaultSceneRoot' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, ReusableAudioComponent) == 0x0004F0, "Member 'AEjectableBounceFxc_C::ReusableAudioComponent' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, BounceAudioEvent) == 0x0004F8, "Member 'AEjectableBounceFxc_C::BounceAudioEvent' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, BounceSurfaceType) == 0x000500, "Member 'AEjectableBounceFxc_C::BounceSurfaceType' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, NumBounces) == 0x000504, "Member 'AEjectableBounceFxc_C::NumBounces' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, BounceSpeed) == 0x000508, "Member 'AEjectableBounceFxc_C::BounceSpeed' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, Ejectable) == 0x000510, "Member 'AEjectableBounceFxc_C::Ejectable' has a wrong offset!");
static_assert(offsetof(AEjectableBounceFxc_C, WWisePerspective) == 0x000518, "Member 'AEjectableBounceFxc_C::WWisePerspective' has a wrong offset!");

}

