#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ExpandMinimapActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ExpandMinimapActionTraits.ExpandMinimapActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UExpandMinimapActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ExpandMinimapActionTraits_C">();
	}
	static class UExpandMinimapActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UExpandMinimapActionTraits_C>();
	}
};
static_assert(alignof(UExpandMinimapActionTraits_C) == 0x000008, "Wrong alignment on UExpandMinimapActionTraits_C");
static_assert(sizeof(UExpandMinimapActionTraits_C) == 0x000040, "Wrong size on UExpandMinimapActionTraits_C");

}

