#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FacialAnimation

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class FacialAnimation.AudioCurveSourceComponent
// 0x0040 (0x0820 - 0x07E0)
class UAudioCurveSourceComponent final : public UAudioComponent
{
public:
	uint8                                         Pad_7E0[0x8];                                      // 0x07E0(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   CurveSourceBindingName;                            // 0x07E8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	float                                         CurveSyncOffset;                                   // 0x07F4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_7F8[0x28];                                     // 0x07F8(0x0028)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioCurveSourceComponent">();
	}
	static class UAudioCurveSourceComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioCurveSourceComponent>();
	}
};
static_assert(alignof(UAudioCurveSourceComponent) == 0x000010, "Wrong alignment on UAudioCurveSourceComponent");
static_assert(sizeof(UAudioCurveSourceComponent) == 0x000820, "Wrong size on UAudioCurveSourceComponent");
static_assert(offsetof(UAudioCurveSourceComponent, CurveSourceBindingName) == 0x0007E8, "Member 'UAudioCurveSourceComponent::CurveSourceBindingName' has a wrong offset!");
static_assert(offsetof(UAudioCurveSourceComponent, CurveSyncOffset) == 0x0007F4, "Member 'UAudioCurveSourceComponent::CurveSyncOffset' has a wrong offset!");

}

