#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FatalVanguardRebootNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FatalVanguardRebootNotification.FatalVanguardRebootNotification_C
// 0x0048 (0x02E0 - 0x0298)
class UFatalVanguardRebootNotification_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 bgcolor;                                           // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ErrorCodeValueLabel;                               // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         GenericErrorCodeContainer;                         // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             IncompatibleSoftware;                              // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         IncompatibleSoftwareContainer;                     // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USharedButtonMaster_C*                  QuitButton;                                        // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USharedButtonMaster_C*                  RebootButton;                                      // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 VanguardLogo;                                      // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FatalVanguardRebootNotification(int32 EntryPoint);
	void Construct();
	void BndEvt__SharedButtonMaster_1_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature();
	void BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature();
	void Update();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FatalVanguardRebootNotification_C">();
	}
	static class UFatalVanguardRebootNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFatalVanguardRebootNotification_C>();
	}
};
static_assert(alignof(UFatalVanguardRebootNotification_C) == 0x000008, "Wrong alignment on UFatalVanguardRebootNotification_C");
static_assert(sizeof(UFatalVanguardRebootNotification_C) == 0x0002E0, "Wrong size on UFatalVanguardRebootNotification_C");
static_assert(offsetof(UFatalVanguardRebootNotification_C, UberGraphFrame) == 0x000298, "Member 'UFatalVanguardRebootNotification_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, bgcolor) == 0x0002A0, "Member 'UFatalVanguardRebootNotification_C::bgcolor' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, ErrorCodeValueLabel) == 0x0002A8, "Member 'UFatalVanguardRebootNotification_C::ErrorCodeValueLabel' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, GenericErrorCodeContainer) == 0x0002B0, "Member 'UFatalVanguardRebootNotification_C::GenericErrorCodeContainer' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, IncompatibleSoftware) == 0x0002B8, "Member 'UFatalVanguardRebootNotification_C::IncompatibleSoftware' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, IncompatibleSoftwareContainer) == 0x0002C0, "Member 'UFatalVanguardRebootNotification_C::IncompatibleSoftwareContainer' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, QuitButton) == 0x0002C8, "Member 'UFatalVanguardRebootNotification_C::QuitButton' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, RebootButton) == 0x0002D0, "Member 'UFatalVanguardRebootNotification_C::RebootButton' has a wrong offset!");
static_assert(offsetof(UFatalVanguardRebootNotification_C, VanguardLogo) == 0x0002D8, "Member 'UFatalVanguardRebootNotification_C::VanguardLogo' has a wrong offset!");

}

