#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FatalVanguardErrorNotification

#include "Basic.hpp"

#include "FatalVanguardErrorNotification_classes.hpp"
#include "FatalVanguardErrorNotification_parameters.hpp"


namespace SDK
{

// Function FatalVanguardErrorNotification.FatalVanguardErrorNotification_C.ExecuteUbergraph_FatalVanguardErrorNotification
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UFatalVanguardErrorNotification_C::ExecuteUbergraph_FatalVanguardErrorNotification(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_FatalVanguardErrorNotification");

	Params::FatalVanguardErrorNotification_C_ExecuteUbergraph_FatalVanguardErrorNotification Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function FatalVanguardErrorNotification.FatalVanguardErrorNotification_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UFatalVanguardErrorNotification_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FatalVanguardErrorNotification.FatalVanguardErrorNotification_C.BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature
// (BlueprintEvent)

void UFatalVanguardErrorNotification_C::BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function FatalVanguardErrorNotification.FatalVanguardErrorNotification_C.Update
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void UFatalVanguardErrorNotification_C::Update()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Update");

	UObject::ProcessEvent(Func, nullptr);
}

}

