#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FatalVanguardErrorNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass FatalVanguardErrorNotification.FatalVanguardErrorNotification_C
// 0x0030 (0x02C8 - 0x0298)
class UFatalVanguardErrorNotification_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 bgcolor;                                           // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ConnectionErrorHeaderText;                         // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             ErrorCodeValueLabel;                               // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         GenericErrorCodeContainer;                         // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USharedButtonMaster_C*                  SharedButtonMaster;                                // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FatalVanguardErrorNotification(int32 EntryPoint);
	void Construct();
	void BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature();
	void Update();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FatalVanguardErrorNotification_C">();
	}
	static class UFatalVanguardErrorNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UFatalVanguardErrorNotification_C>();
	}
};
static_assert(alignof(UFatalVanguardErrorNotification_C) == 0x000008, "Wrong alignment on UFatalVanguardErrorNotification_C");
static_assert(sizeof(UFatalVanguardErrorNotification_C) == 0x0002C8, "Wrong size on UFatalVanguardErrorNotification_C");
static_assert(offsetof(UFatalVanguardErrorNotification_C, UberGraphFrame) == 0x000298, "Member 'UFatalVanguardErrorNotification_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UFatalVanguardErrorNotification_C, bgcolor) == 0x0002A0, "Member 'UFatalVanguardErrorNotification_C::bgcolor' has a wrong offset!");
static_assert(offsetof(UFatalVanguardErrorNotification_C, ConnectionErrorHeaderText) == 0x0002A8, "Member 'UFatalVanguardErrorNotification_C::ConnectionErrorHeaderText' has a wrong offset!");
static_assert(offsetof(UFatalVanguardErrorNotification_C, ErrorCodeValueLabel) == 0x0002B0, "Member 'UFatalVanguardErrorNotification_C::ErrorCodeValueLabel' has a wrong offset!");
static_assert(offsetof(UFatalVanguardErrorNotification_C, GenericErrorCodeContainer) == 0x0002B8, "Member 'UFatalVanguardErrorNotification_C::GenericErrorCodeContainer' has a wrong offset!");
static_assert(offsetof(UFatalVanguardErrorNotification_C, SharedButtonMaster) == 0x0002C0, "Member 'UFatalVanguardErrorNotification_C::SharedButtonMaster' has a wrong offset!");

}

