#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GenericTextTooltipContractVault

#include "Basic.hpp"

#include "GenericTextTooltipContractVault_classes.hpp"
#include "GenericTextTooltipContractVault_parameters.hpp"


namespace SDK
{

// Function GenericTextTooltipContractVault.GenericTextTooltipContractVault_C.ExecuteUbergraph_GenericTextTooltipContractVault
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGenericTextTooltipContractVault_C::ExecuteUbergraph_GenericTextTooltipContractVault(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_GenericTextTooltipContractVault");

	Params::GenericTextTooltipContractVault_C_ExecuteUbergraph_GenericTextTooltipContractVault Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GenericTextTooltipContractVault.GenericTextTooltipContractVault_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UGenericTextTooltipContractVault_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GenericTextTooltipContractVault.GenericTextTooltipContractVault_C.PlayOutroAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void UGenericTextTooltipContractVault_C::PlayOutroAnimation()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PlayOutroAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GenericTextTooltipContractVault.GenericTextTooltipContractVault_C.SetText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NewContent                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void UGenericTextTooltipContractVault_C::SetText(const class FText& NewContent)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetText");

	Params::GenericTextTooltipContractVault_C_SetText Parms{};

	Parms.NewContent = std::move(NewContent);

	UObject::ProcessEvent(Func, &Parms);
}

}

