#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GenericTextTooltip

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass GenericTextTooltip.GenericTextTooltip_C
// 0x0038 (0x02D0 - 0x0298)
class UGenericTextTooltip_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UGenericTooltipWrapper_C*               GenericTooltipWrapper;                             // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             TooltipTextBlock;                                  // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   TooltipTextContent;                                // 0x02B0(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)
	float                                         AutoWrapWidth;                                     // 0x02C8(0x0004)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GenericTextTooltip(int32 EntryPoint);
	void Construct();
	void PlayOutroAnimation();
	void SetText(const class FText& NewContent);
	ESlateVisibility GetVisibility_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GenericTextTooltip_C">();
	}
	static class UGenericTextTooltip_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGenericTextTooltip_C>();
	}
};
static_assert(alignof(UGenericTextTooltip_C) == 0x000008, "Wrong alignment on UGenericTextTooltip_C");
static_assert(sizeof(UGenericTextTooltip_C) == 0x0002D0, "Wrong size on UGenericTextTooltip_C");
static_assert(offsetof(UGenericTextTooltip_C, UberGraphFrame) == 0x000298, "Member 'UGenericTextTooltip_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGenericTextTooltip_C, GenericTooltipWrapper) == 0x0002A0, "Member 'UGenericTextTooltip_C::GenericTooltipWrapper' has a wrong offset!");
static_assert(offsetof(UGenericTextTooltip_C, TooltipTextBlock) == 0x0002A8, "Member 'UGenericTextTooltip_C::TooltipTextBlock' has a wrong offset!");
static_assert(offsetof(UGenericTextTooltip_C, TooltipTextContent) == 0x0002B0, "Member 'UGenericTextTooltip_C::TooltipTextContent' has a wrong offset!");
static_assert(offsetof(UGenericTextTooltip_C, AutoWrapWidth) == 0x0002C8, "Member 'UGenericTextTooltip_C::AutoWrapWidth' has a wrong offset!");

}

