#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GenericTooltipWrapper

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass GenericTooltipWrapper.GenericTooltipWrapper_C
// 0x0048 (0x02E0 - 0x0298)
class UGenericTooltipWrapper_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Intro;                                             // 0x02A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UBackgroundBlur*                        BackgroundBlur_172;                                // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UNamedSlot*                             Content;                                           // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 Subject;                                           // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, ExposeOnSpawn, HasGetValueTypeHash)
	class FText                                   DisplayName;                                       // 0x02C8(0x0018)(Edit, BlueprintVisible, ExposeOnSpawn)

public:
	void ExecuteUbergraph_GenericTooltipWrapper(int32 EntryPoint);
	void Construct();
	void PlayOutroAnimation();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GenericTooltipWrapper_C">();
	}
	static class UGenericTooltipWrapper_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGenericTooltipWrapper_C>();
	}
};
static_assert(alignof(UGenericTooltipWrapper_C) == 0x000008, "Wrong alignment on UGenericTooltipWrapper_C");
static_assert(sizeof(UGenericTooltipWrapper_C) == 0x0002E0, "Wrong size on UGenericTooltipWrapper_C");
static_assert(offsetof(UGenericTooltipWrapper_C, UberGraphFrame) == 0x000298, "Member 'UGenericTooltipWrapper_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGenericTooltipWrapper_C, Intro) == 0x0002A0, "Member 'UGenericTooltipWrapper_C::Intro' has a wrong offset!");
static_assert(offsetof(UGenericTooltipWrapper_C, BackgroundBlur_172) == 0x0002A8, "Member 'UGenericTooltipWrapper_C::BackgroundBlur_172' has a wrong offset!");
static_assert(offsetof(UGenericTooltipWrapper_C, Content) == 0x0002B0, "Member 'UGenericTooltipWrapper_C::Content' has a wrong offset!");
static_assert(offsetof(UGenericTooltipWrapper_C, Subject) == 0x0002B8, "Member 'UGenericTooltipWrapper_C::Subject' has a wrong offset!");
static_assert(offsetof(UGenericTooltipWrapper_C, DisplayName) == 0x0002C8, "Member 'UGenericTooltipWrapper_C::DisplayName' has a wrong offset!");

}

