#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GenericTooltipWrapper

#include "Basic.hpp"


namespace SDK::Params
{

// Function GenericTooltipWrapper.GenericTooltipWrapper_C.ExecuteUbergraph_GenericTooltipWrapper
// 0x0010 (0x0010 - 0x0000)
struct GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper) == 0x000008, "Wrong alignment on GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper");
static_assert(sizeof(GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper) == 0x000010, "Wrong size on GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper");
static_assert(offsetof(GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper, EntryPoint) == 0x000000, "Member 'GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper::EntryPoint' has a wrong offset!");
static_assert(offsetof(GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'GenericTooltipWrapper_C_ExecuteUbergraph_GenericTooltipWrapper::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

// Function GenericTooltipWrapper.GenericTooltipWrapper_C.PlayOutroAnimation
// 0x0008 (0x0008 - 0x0000)
struct GenericTooltipWrapper_C_PlayOutroAnimation final
{
public:
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GenericTooltipWrapper_C_PlayOutroAnimation) == 0x000008, "Wrong alignment on GenericTooltipWrapper_C_PlayOutroAnimation");
static_assert(sizeof(GenericTooltipWrapper_C_PlayOutroAnimation) == 0x000008, "Wrong size on GenericTooltipWrapper_C_PlayOutroAnimation");
static_assert(offsetof(GenericTooltipWrapper_C_PlayOutroAnimation, CallFunc_PlayAnimation_ReturnValue) == 0x000000, "Member 'GenericTooltipWrapper_C_PlayOutroAnimation::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

}

