#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GhostActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GhostActionTraits.GhostActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UGhostActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GhostActionTraits_C">();
	}
	static class UGhostActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGhostActionTraits_C>();
	}
};
static_assert(alignof(UGhostActionTraits_C) == 0x000008, "Wrong alignment on UGhostActionTraits_C");
static_assert(sizeof(UGhostActionTraits_C) == 0x000040, "Wrong size on UGhostActionTraits_C");

}

