#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GlobalAudioManagerBP

#include "Basic.hpp"

#include "GlobalAudioManagerBP_classes.hpp"
#include "GlobalAudioManagerBP_parameters.hpp"


namespace SDK
{

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.ExecuteUbergraph_GlobalAudioManagerBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGlobalAudioManagerBP_C::ExecuteUbergraph_GlobalAudioManagerBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_GlobalAudioManagerBP");

	Params::GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.HandleCurrentMenuMusicChanged
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FMenuMusic                       NewValue                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UGlobalAudioManagerBP_C::HandleCurrentMenuMusicChanged(const struct FMenuMusic& NewValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleCurrentMenuMusicChanged");

	Params::GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged Parms{};

	Parms.NewValue = std::move(NewValue);

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnApplicationActivationStateChange
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bActive                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobalAudioManagerBP_C::OnApplicationActivationStateChange(bool bActive)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnApplicationActivationStateChange");

	Params::GlobalAudioManagerBP_C_OnApplicationActivationStateChange Parms{};

	Parms.bActive = bActive;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.EndPregame
// (Event, Public, BlueprintEvent)

void UGlobalAudioManagerBP_C::EndPregame()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("EndPregame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnMatchmakingChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewValue                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobalAudioManagerBP_C::OnMatchmakingChanged(const bool NewValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMatchmakingChanged");

	Params::GlobalAudioManagerBP_C_OnMatchmakingChanged Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.BeginTransitionToPregame
// (Event, Public, BlueprintEvent)

void UGlobalAudioManagerBP_C::BeginTransitionToPregame()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BeginTransitionToPregame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnMatchFound
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewValue                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobalAudioManagerBP_C::OnMatchFound(const bool NewValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMatchFound");

	Params::GlobalAudioManagerBP_C_OnMatchFound Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.UpdateMenuMusic
// (BlueprintCallable, BlueprintEvent)

void UGlobalAudioManagerBP_C::UpdateMenuMusic()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateMenuMusic");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnWinningTeam
// (Event, Public, BlueprintEvent)
// Parameters:
// class UBaseTeamComponent*               WinningTeam                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGlobalAudioManagerBP_C::OnWinningTeam(const class UBaseTeamComponent* WinningTeam)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnWinningTeam");

	Params::GlobalAudioManagerBP_C_OnWinningTeam Parms{};

	Parms.WinningTeam = WinningTeam;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.BeginInitialization
// (Event, Public, BlueprintEvent)

void UGlobalAudioManagerBP_C::BeginInitialization()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BeginInitialization");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.BeginInGame
// (Event, Public, BlueprintEvent)

void UGlobalAudioManagerBP_C::BeginInGame()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BeginInGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.BeginTransitionToInGame
// (Event, Public, BlueprintEvent)

void UGlobalAudioManagerBP_C::BeginTransitionToInGame()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BeginTransitionToInGame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnLockInChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    NewValue                                               (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void UGlobalAudioManagerBP_C::OnLockInChanged(const bool NewValue)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnLockInChanged");

	Params::GlobalAudioManagerBP_C_OnLockInChanged Parms{};

	Parms.NewValue = NewValue;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.BeginMainMenu
// (Event, Public, BlueprintEvent)

void UGlobalAudioManagerBP_C::BeginMainMenu()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BeginMainMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.BeginPregame
// (Event, Public, BlueprintEvent)

void UGlobalAudioManagerBP_C::BeginPregame()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BeginPregame");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.PartySizeChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPartyPlayerModel*                Player                                                 (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGlobalAudioManagerBP_C::PartySizeChanged(const class UPartyPlayerModel* Player)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PartySizeChanged");

	Params::GlobalAudioManagerBP_C_PartySizeChanged Parms{};

	Parms.Player = Player;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.UpdatePregameMusic
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UPregameViewModel*                PregameViewModel                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGlobalAudioManagerBP_C::UpdatePregameMusic(class UPregameViewModel* PregameViewModel)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdatePregameMusic");

	Params::GlobalAudioManagerBP_C_UpdatePregameMusic Parms{};

	Parms.PregameViewModel = PregameViewModel;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.GetMainMenuNavigationMusic
// (Public, HasOutParams, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EAresMainMenuTopNavigationState         State                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// struct FMenuMusic                       NewParam                                               (Parm, OutParm, NoDestructor)

void UGlobalAudioManagerBP_C::GetMainMenuNavigationMusic(EAresMainMenuTopNavigationState State, struct FMenuMusic* NewParam)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetMainMenuNavigationMusic");

	Params::GlobalAudioManagerBP_C_GetMainMenuNavigationMusic Parms{};

	Parms.State = State;

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = std::move(Parms.NewParam);
}

}

