#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GlobalAudioManagerBP

#include "Basic.hpp"

#include "ShooterGame_structs.hpp"


namespace SDK::Params
{

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.ExecuteUbergraph_GlobalAudioManagerBP
// 0x0340 (0x0340 - 0x0000)
struct GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate;              // 0x0008(0x0014)(ZeroConstructor, NoDestructor)
	bool                                          Temp_bool_Variable_1;                              // 0x001C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_2;                              // 0x001D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1E[0x2];                                       // 0x001E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue;    // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPartyViewController*                   CallFunc_GetPartyViewController_ReturnValue;       // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UPartyPlayerModel*                K2Node_CustomEvent_Player;                         // 0x0030(0x0008)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_3;                              // 0x0038(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class APlayerController*                      CallFunc_GetFirstLocalPlayerController_ReturnValue; // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APregamePlayerController_C*             K2Node_DynamicCast_AsPregame_Player_Controller;    // 0x0048(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0050(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          Temp_bool_Variable_4;                              // 0x0051(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_52[0x6];                                       // 0x0052(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UPregameViewModel*                      CallFunc_GetViewModel_ReturnValue;                 // 0x0058(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_NewValue_3;                     // 0x0060(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_61[0x7];                                       // 0x0061(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AOwnerExclusivePlayerInfo*              CallFunc_GetLocalPlayerInfo_ReturnValue;           // 0x0068(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	const class UBaseTeamComponent*               K2Node_Event_WinningTeam;                          // 0x0070(0x0008)(ConstParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AShooterPlayerState*                    CallFunc_GetPlayerState_ReturnValue;               // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UBaseTeamComponent*                     CallFunc_GetTeamComponent_ReturnValue;             // 0x0080(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APlayerController*                      CallFunc_GetPlayerController_ReturnValue;          // 0x0088(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsTeamAlly_ReturnValue;                   // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class ABaseMainMenuPlayerController*          K2Node_DynamicCast_AsBase_Main_Menu_Player_Controller; // 0x0098(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x00A0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_A1[0x7];                                       // 0x00A1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue_1;  // 0x00A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable_5;                              // 0x00B0(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B1[0x7];                                       // 0x00B1(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameFlowStateManager*                  CallFunc_GetGameFlowStateManager_ReturnValue;      // 0x00B8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UGameFlowState*                         CallFunc_GetState_ReturnValue;                     // 0x00C0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_CustomEvent_NewValue_2;                     // 0x00C8(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C9[0x7];                                       // 0x00C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UMainMenuStateV2*                       K2Node_DynamicCast_AsMain_Menu_State_V2;           // 0x00D0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x00D8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x00D9(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_DA[0x2];                                       // 0x00DA(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(class UPartyPlayerModel* Player)> K2Node_CreateDelegate_OutputDelegate_1;            // 0x00DC(0x0014)(ZeroConstructor, NoDestructor)
	class AGameStateBase*                         CallFunc_GetGameState_ReturnValue;                 // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AShooterGameState*                      K2Node_DynamicCast_AsShooter_Game_State;           // 0x00F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0100(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsChildOfClass_ReturnValue;               // 0x0101(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_102[0x6];                                      // 0x0102(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FAresRoundResult>               CallFunc_GetRoundResults_ReturnValue;              // 0x0108(0x0010)(ConstParm, ZeroConstructor, ReferenceParm)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0118(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_IntInt_ReturnValue;            // 0x011C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_CustomEvent_NewValue_1;                     // 0x011D(0x0001)(ConstParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_11E[0x2];                                      // 0x011E(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue_2;  // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EProvisioningFlowID                           Temp_byte_Variable;                                // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_129[0x7];                                      // 0x0129(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UGameFlowStateManager*                  CallFunc_GetGameFlowStateManager_ReturnValue_1;    // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EGameFlowStateType                            CallFunc_GetCurrentStateType_ReturnValue;          // 0x0138(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_NotEqual_ByteByte_ReturnValue;            // 0x0139(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Event_bActive;                              // 0x013A(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_13B[0x5];                                      // 0x013B(0x0005)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue_3;  // 0x0140(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_2;            // 0x0148(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_15C[0x4];                                      // 0x015C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPartyViewController*                   CallFunc_GetPartyViewController_ReturnValue_1;     // 0x0160(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMatchmaking_ReturnValue;                // 0x0168(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_169[0x3];                                      // 0x0169(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	TDelegate<void(struct FMenuMusic& NewValue)>  K2Node_CreateDelegate_OutputDelegate_3;            // 0x016C(0x0014)(ZeroConstructor, NoDestructor)
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue_4;  // 0x0180(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMenuMusic                             K2Node_CustomEvent_NewValue;                       // 0x0188(0x0010)(ConstParm, NoDestructor)
	class UMenuStackManager*                      CallFunc_GetMenuStackManager_ReturnValue;          // 0x0198(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue_5;  // 0x01A0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UMenuStackManager*                      CallFunc_GetMenuStackManager_ReturnValue_1;        // 0x01A8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate_4;            // 0x01B0(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_1C4[0x4];                                      // 0x01C4(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMenuMusic                             CallFunc_GetCurrentMenuMusic_ReturnValue;          // 0x01C8(0x0010)(NoDestructor)
	TDelegate<void(bool NewValue)>                K2Node_CreateDelegate_OutputDelegate_5;            // 0x01D8(0x0014)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x01EC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x01ED(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1EE[0x2];                                      // 0x01EE(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue_6;  // 0x01F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UCoreGameManager*                       CallFunc_GetCoreGameManager_ReturnValue;           // 0x01F8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FCoreGameMatchDTO                      CallFunc_GetCurrentMatch_Match;                    // 0x0200(0x0138)()
	bool                                          CallFunc_GetCurrentMatch_ReturnValue;              // 0x0338(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          K2Node_Select_Default;                             // 0x0339(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP) == 0x000008, "Wrong alignment on GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP");
static_assert(sizeof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP) == 0x000340, "Wrong size on GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, EntryPoint) == 0x000000, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, Temp_bool_Variable) == 0x000004, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CreateDelegate_OutputDelegate) == 0x000008, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, Temp_bool_Variable_1) == 0x00001C, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::Temp_bool_Variable_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, Temp_bool_Variable_2) == 0x00001D, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::Temp_bool_Variable_2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetAresClientGameInstance_ReturnValue) == 0x000020, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetAresClientGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetPartyViewController_ReturnValue) == 0x000028, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetPartyViewController_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CustomEvent_Player) == 0x000030, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CustomEvent_Player' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, Temp_bool_Variable_3) == 0x000038, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::Temp_bool_Variable_3' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetFirstLocalPlayerController_ReturnValue) == 0x000040, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetFirstLocalPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_AsPregame_Player_Controller) == 0x000048, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_AsPregame_Player_Controller' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_bSuccess) == 0x000050, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, Temp_bool_Variable_4) == 0x000051, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::Temp_bool_Variable_4' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetViewModel_ReturnValue) == 0x000058, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetViewModel_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CustomEvent_NewValue_3) == 0x000060, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CustomEvent_NewValue_3' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetLocalPlayerInfo_ReturnValue) == 0x000068, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetLocalPlayerInfo_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_Event_WinningTeam) == 0x000070, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_Event_WinningTeam' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetPlayerState_ReturnValue) == 0x000078, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetPlayerState_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetTeamComponent_ReturnValue) == 0x000080, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetTeamComponent_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetPlayerController_ReturnValue) == 0x000088, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetPlayerController_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_IsTeamAlly_ReturnValue) == 0x000090, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_IsTeamAlly_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_AsBase_Main_Menu_Player_Controller) == 0x000098, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_AsBase_Main_Menu_Player_Controller' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_bSuccess_1) == 0x0000A0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetAresClientGameInstance_ReturnValue_1) == 0x0000A8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetAresClientGameInstance_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, Temp_bool_Variable_5) == 0x0000B0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::Temp_bool_Variable_5' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetGameFlowStateManager_ReturnValue) == 0x0000B8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetGameFlowStateManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetState_ReturnValue) == 0x0000C0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetState_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CustomEvent_NewValue_2) == 0x0000C8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CustomEvent_NewValue_2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_AsMain_Menu_State_V2) == 0x0000D0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_AsMain_Menu_State_V2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_bSuccess_2) == 0x0000D8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_IsValid_ReturnValue) == 0x0000D9, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CreateDelegate_OutputDelegate_1) == 0x0000DC, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetGameState_ReturnValue) == 0x0000F0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetGameState_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_AsShooter_Game_State) == 0x0000F8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_AsShooter_Game_State' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_DynamicCast_bSuccess_3) == 0x000100, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_IsChildOfClass_ReturnValue) == 0x000101, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_IsChildOfClass_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetRoundResults_ReturnValue) == 0x000108, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetRoundResults_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_Array_Length_ReturnValue) == 0x000118, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_EqualEqual_IntInt_ReturnValue) == 0x00011C, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_EqualEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CustomEvent_NewValue_1) == 0x00011D, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CustomEvent_NewValue_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetAresClientGameInstance_ReturnValue_2) == 0x000120, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetAresClientGameInstance_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, Temp_byte_Variable) == 0x000128, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetGameFlowStateManager_ReturnValue_1) == 0x000130, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetGameFlowStateManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetCurrentStateType_ReturnValue) == 0x000138, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetCurrentStateType_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_NotEqual_ByteByte_ReturnValue) == 0x000139, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_NotEqual_ByteByte_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_Event_bActive) == 0x00013A, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_Event_bActive' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetAresClientGameInstance_ReturnValue_3) == 0x000140, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetAresClientGameInstance_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CreateDelegate_OutputDelegate_2) == 0x000148, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetPartyViewController_ReturnValue_1) == 0x000160, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetPartyViewController_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_IsMatchmaking_ReturnValue) == 0x000168, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_IsMatchmaking_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CreateDelegate_OutputDelegate_3) == 0x00016C, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetAresClientGameInstance_ReturnValue_4) == 0x000180, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetAresClientGameInstance_ReturnValue_4' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CustomEvent_NewValue) == 0x000188, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CustomEvent_NewValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetMenuStackManager_ReturnValue) == 0x000198, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetMenuStackManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetAresClientGameInstance_ReturnValue_5) == 0x0001A0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetAresClientGameInstance_ReturnValue_5' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetMenuStackManager_ReturnValue_1) == 0x0001A8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetMenuStackManager_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CreateDelegate_OutputDelegate_4) == 0x0001B0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CreateDelegate_OutputDelegate_4' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetCurrentMenuMusic_ReturnValue) == 0x0001C8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetCurrentMenuMusic_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_CreateDelegate_OutputDelegate_5) == 0x0001D8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_CreateDelegate_OutputDelegate_5' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_IsValid_ReturnValue_1) == 0x0001EC, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_IsValid_ReturnValue_2) == 0x0001ED, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetAresClientGameInstance_ReturnValue_6) == 0x0001F0, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetAresClientGameInstance_ReturnValue_6' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetCoreGameManager_ReturnValue) == 0x0001F8, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetCoreGameManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetCurrentMatch_Match) == 0x000200, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetCurrentMatch_Match' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, CallFunc_GetCurrentMatch_ReturnValue) == 0x000338, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::CallFunc_GetCurrentMatch_ReturnValue' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP, K2Node_Select_Default) == 0x000339, "Member 'GlobalAudioManagerBP_C_ExecuteUbergraph_GlobalAudioManagerBP::K2Node_Select_Default' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.HandleCurrentMenuMusicChanged
// 0x0010 (0x0010 - 0x0000)
struct GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged final
{
public:
	struct FMenuMusic                             NewValue;                                          // 0x0000(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged) == 0x000008, "Wrong alignment on GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged");
static_assert(sizeof(GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged) == 0x000010, "Wrong size on GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged");
static_assert(offsetof(GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged, NewValue) == 0x000000, "Member 'GlobalAudioManagerBP_C_HandleCurrentMenuMusicChanged::NewValue' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnApplicationActivationStateChange
// 0x0001 (0x0001 - 0x0000)
struct GlobalAudioManagerBP_C_OnApplicationActivationStateChange final
{
public:
	bool                                          bActive;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_OnApplicationActivationStateChange) == 0x000001, "Wrong alignment on GlobalAudioManagerBP_C_OnApplicationActivationStateChange");
static_assert(sizeof(GlobalAudioManagerBP_C_OnApplicationActivationStateChange) == 0x000001, "Wrong size on GlobalAudioManagerBP_C_OnApplicationActivationStateChange");
static_assert(offsetof(GlobalAudioManagerBP_C_OnApplicationActivationStateChange, bActive) == 0x000000, "Member 'GlobalAudioManagerBP_C_OnApplicationActivationStateChange::bActive' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnMatchmakingChanged
// 0x0001 (0x0001 - 0x0000)
struct GlobalAudioManagerBP_C_OnMatchmakingChanged final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_OnMatchmakingChanged) == 0x000001, "Wrong alignment on GlobalAudioManagerBP_C_OnMatchmakingChanged");
static_assert(sizeof(GlobalAudioManagerBP_C_OnMatchmakingChanged) == 0x000001, "Wrong size on GlobalAudioManagerBP_C_OnMatchmakingChanged");
static_assert(offsetof(GlobalAudioManagerBP_C_OnMatchmakingChanged, NewValue) == 0x000000, "Member 'GlobalAudioManagerBP_C_OnMatchmakingChanged::NewValue' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnMatchFound
// 0x0001 (0x0001 - 0x0000)
struct GlobalAudioManagerBP_C_OnMatchFound final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_OnMatchFound) == 0x000001, "Wrong alignment on GlobalAudioManagerBP_C_OnMatchFound");
static_assert(sizeof(GlobalAudioManagerBP_C_OnMatchFound) == 0x000001, "Wrong size on GlobalAudioManagerBP_C_OnMatchFound");
static_assert(offsetof(GlobalAudioManagerBP_C_OnMatchFound, NewValue) == 0x000000, "Member 'GlobalAudioManagerBP_C_OnMatchFound::NewValue' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnWinningTeam
// 0x0008 (0x0008 - 0x0000)
struct GlobalAudioManagerBP_C_OnWinningTeam final
{
public:
	const class UBaseTeamComponent*               WinningTeam;                                       // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GlobalAudioManagerBP_C_OnWinningTeam) == 0x000008, "Wrong alignment on GlobalAudioManagerBP_C_OnWinningTeam");
static_assert(sizeof(GlobalAudioManagerBP_C_OnWinningTeam) == 0x000008, "Wrong size on GlobalAudioManagerBP_C_OnWinningTeam");
static_assert(offsetof(GlobalAudioManagerBP_C_OnWinningTeam, WinningTeam) == 0x000000, "Member 'GlobalAudioManagerBP_C_OnWinningTeam::WinningTeam' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.OnLockInChanged
// 0x0001 (0x0001 - 0x0000)
struct GlobalAudioManagerBP_C_OnLockInChanged final
{
public:
	bool                                          NewValue;                                          // 0x0000(0x0001)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_OnLockInChanged) == 0x000001, "Wrong alignment on GlobalAudioManagerBP_C_OnLockInChanged");
static_assert(sizeof(GlobalAudioManagerBP_C_OnLockInChanged) == 0x000001, "Wrong size on GlobalAudioManagerBP_C_OnLockInChanged");
static_assert(offsetof(GlobalAudioManagerBP_C_OnLockInChanged, NewValue) == 0x000000, "Member 'GlobalAudioManagerBP_C_OnLockInChanged::NewValue' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.PartySizeChanged
// 0x0008 (0x0008 - 0x0000)
struct GlobalAudioManagerBP_C_PartySizeChanged final
{
public:
	const class UPartyPlayerModel*                Player;                                            // 0x0000(0x0008)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(GlobalAudioManagerBP_C_PartySizeChanged) == 0x000008, "Wrong alignment on GlobalAudioManagerBP_C_PartySizeChanged");
static_assert(sizeof(GlobalAudioManagerBP_C_PartySizeChanged) == 0x000008, "Wrong size on GlobalAudioManagerBP_C_PartySizeChanged");
static_assert(offsetof(GlobalAudioManagerBP_C_PartySizeChanged, Player) == 0x000000, "Member 'GlobalAudioManagerBP_C_PartySizeChanged::Player' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.UpdatePregameMusic
// 0x0010 (0x0010 - 0x0000)
struct GlobalAudioManagerBP_C_UpdatePregameMusic final
{
public:
	class UPregameViewModel*                      PregameViewModel;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsLocalPlayerLockedIn_ReturnValue;        // 0x0008(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_UpdatePregameMusic) == 0x000008, "Wrong alignment on GlobalAudioManagerBP_C_UpdatePregameMusic");
static_assert(sizeof(GlobalAudioManagerBP_C_UpdatePregameMusic) == 0x000010, "Wrong size on GlobalAudioManagerBP_C_UpdatePregameMusic");
static_assert(offsetof(GlobalAudioManagerBP_C_UpdatePregameMusic, PregameViewModel) == 0x000000, "Member 'GlobalAudioManagerBP_C_UpdatePregameMusic::PregameViewModel' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_UpdatePregameMusic, CallFunc_IsLocalPlayerLockedIn_ReturnValue) == 0x000008, "Member 'GlobalAudioManagerBP_C_UpdatePregameMusic::CallFunc_IsLocalPlayerLockedIn_ReturnValue' has a wrong offset!");

// Function GlobalAudioManagerBP.GlobalAudioManagerBP_C.GetMainMenuNavigationMusic
// 0x00A0 (0x00A0 - 0x0000)
struct GlobalAudioManagerBP_C_GetMainMenuNavigationMusic final
{
public:
	EAresMainMenuTopNavigationState               State;                                             // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMenuMusic                             NewParam;                                          // 0x0008(0x0010)(Parm, OutParm, NoDestructor)
	EAresMainMenuTopNavigationState               Temp_byte_Variable;                                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_19[0x7];                                       // 0x0019(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FMenuMusic                             K2Node_MakeStruct_MenuMusic;                       // 0x0020(0x0010)(NoDestructor)
	struct FMenuMusic                             K2Node_MakeStruct_MenuMusic_1;                     // 0x0030(0x0010)(NoDestructor)
	struct FMenuMusic                             K2Node_MakeStruct_MenuMusic_2;                     // 0x0040(0x0010)(NoDestructor)
	struct FMenuMusic                             K2Node_MakeStruct_MenuMusic_3;                     // 0x0050(0x0010)(NoDestructor)
	struct FMenuMusic                             K2Node_MakeStruct_MenuMusic_4;                     // 0x0060(0x0010)(NoDestructor)
	struct FMenuMusic                             K2Node_MakeStruct_MenuMusic_5;                     // 0x0070(0x0010)(NoDestructor)
	struct FMenuMusic                             K2Node_MakeStruct_MenuMusic_6;                     // 0x0080(0x0010)(NoDestructor)
	struct FMenuMusic                             K2Node_Select_Default;                             // 0x0090(0x0010)(NoDestructor)
};
static_assert(alignof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic) == 0x000008, "Wrong alignment on GlobalAudioManagerBP_C_GetMainMenuNavigationMusic");
static_assert(sizeof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic) == 0x0000A0, "Wrong size on GlobalAudioManagerBP_C_GetMainMenuNavigationMusic");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, State) == 0x000000, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::State' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, NewParam) == 0x000008, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::NewParam' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, Temp_byte_Variable) == 0x000018, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_MakeStruct_MenuMusic) == 0x000020, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_MakeStruct_MenuMusic' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_MakeStruct_MenuMusic_1) == 0x000030, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_MakeStruct_MenuMusic_1' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_MakeStruct_MenuMusic_2) == 0x000040, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_MakeStruct_MenuMusic_2' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_MakeStruct_MenuMusic_3) == 0x000050, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_MakeStruct_MenuMusic_3' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_MakeStruct_MenuMusic_4) == 0x000060, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_MakeStruct_MenuMusic_4' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_MakeStruct_MenuMusic_5) == 0x000070, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_MakeStruct_MenuMusic_5' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_MakeStruct_MenuMusic_6) == 0x000080, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_MakeStruct_MenuMusic_6' has a wrong offset!");
static_assert(offsetof(GlobalAudioManagerBP_C_GetMainMenuNavigationMusic, K2Node_Select_Default) == 0x000090, "Member 'GlobalAudioManagerBP_C_GetMainMenuNavigationMusic::K2Node_Select_Default' has a wrong offset!");

}

