#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Init

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Init.Init_C
// 0x0000 (0x03B0 - 0x03B0)
class AInit_C final : public ALevelScriptActor
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Init_C">();
	}
	static class AInit_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AInit_C>();
	}
};
static_assert(alignof(AInit_C) == 0x000008, "Wrong alignment on AInit_C");
static_assert(sizeof(AInit_C) == 0x0003B0, "Wrong size on AInit_C");

}

