#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InitScreen

#include "Basic.hpp"

#include "InitScreen_classes.hpp"
#include "InitScreen_parameters.hpp"


namespace SDK
{

// Function InitScreen.InitScreen_C.ExecuteUbergraph_InitScreen
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UInitScreen_C::ExecuteUbergraph_InitScreen(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_InitScreen");

	Params::InitScreen_C_ExecuteUbergraph_InitScreen Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function InitScreen.InitScreen_C.BndEvt__Skip_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UInitScreen_C::BndEvt__Skip_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__Skip_K2Node_ComponentBoundEvent_1_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.ShowSplashScreens
// (BlueprintCallable, BlueprintEvent)

void UInitScreen_C::ShowSplashScreens()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ShowSplashScreens");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.OnPatchContentUpToDate
// (BlueprintCallable, BlueprintEvent)

void UInitScreen_C::OnPatchContentUpToDate()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnPatchContentUpToDate");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.MountContentAndUpdateState
// (BlueprintCallable, BlueprintEvent)

void UInitScreen_C::MountContentAndUpdateState()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("MountContentAndUpdateState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.OnLoginReady
// (BlueprintCallable, BlueprintEvent)

void UInitScreen_C::OnLoginReady()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnLoginReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.OnQueueUpdated
// (BlueprintCallable, BlueprintEvent)

void UInitScreen_C::OnQueueUpdated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnQueueUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.BndEvt__LogoutButtonShared_K2Node_ComponentBoundEvent_8_Clicked__DelegateSignature
// (BlueprintEvent)

void UInitScreen_C::BndEvt__LogoutButtonShared_K2Node_ComponentBoundEvent_8_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__LogoutButtonShared_K2Node_ComponentBoundEvent_8_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.BndEvt__ShipLogoutShared_K2Node_ComponentBoundEvent_7_Clicked__DelegateSignature
// (BlueprintEvent)

void UInitScreen_C::BndEvt__ShipLogoutShared_K2Node_ComponentBoundEvent_7_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__ShipLogoutShared_K2Node_ComponentBoundEvent_7_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.BndEvt__ShipQuitShared_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature
// (BlueprintEvent)

void UInitScreen_C::BndEvt__ShipQuitShared_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__ShipQuitShared_K2Node_ComponentBoundEvent_3_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.BndEvt__QuitButtonShared_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature
// (BlueprintEvent)

void UInitScreen_C::BndEvt__QuitButtonShared_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__QuitButtonShared_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.OnAnimationFinished
// (BlueprintCosmetic, Event, Protected, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 Animation                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UInitScreen_C::OnAnimationFinished(const class UWidgetAnimation* Animation)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnAnimationFinished");

	Params::InitScreen_C_OnAnimationFinished Parms{};

	Parms.Animation = Animation;

	UObject::ProcessEvent(Func, &Parms);
}


// Function InitScreen.InitScreen_C.OnClientGameInstanceInitStatusChanged
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// EAresClientGameInstanceInitStatus       Status                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class FText                             ErrorCode                                              (BlueprintVisible, BlueprintReadOnly, Parm)

void UInitScreen_C::OnClientGameInstanceInitStatusChanged(EAresClientGameInstanceInitStatus Status, const class FText& ErrorCode)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnClientGameInstanceInitStatusChanged");

	Params::InitScreen_C_OnClientGameInstanceInitStatusChanged Parms{};

	Parms.Status = Status;
	Parms.ErrorCode = std::move(ErrorCode);

	UObject::ProcessEvent(Func, &Parms);
}


// Function InitScreen.InitScreen_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UInitScreen_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.TransitionToMainMenu
// (Public, BlueprintCallable, BlueprintEvent)

void UInitScreen_C::TransitionToMainMenu()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionToMainMenu");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.UpdateState
// (Public, BlueprintCallable, BlueprintEvent)

void UInitScreen_C::UpdateState()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateState");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.GetErrorWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          Widget                                                 (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UInitScreen_C::GetErrorWidget(class UWidget** Widget)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetErrorWidget");

	Params::InitScreen_C_GetErrorWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Widget != nullptr)
		*Widget = Parms.Widget;
}


// Function InitScreen.InitScreen_C.UpdateLocalizationOverrides
// (Public, BlueprintCallable, BlueprintEvent)

void UInitScreen_C::UpdateLocalizationOverrides()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateLocalizationOverrides");

	UObject::ProcessEvent(Func, nullptr);
}


// Function InitScreen.InitScreen_C.GetInitializingWidget
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class UWidget*                          NewParam                                               (Parm, OutParm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UInitScreen_C::GetInitializingWidget(class UWidget** NewParam)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetInitializingWidget");

	Params::InitScreen_C_GetInitializingWidget Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (NewParam != nullptr)
		*NewParam = Parms.NewParam;
}


// Function InitScreen.InitScreen_C.GetRequiresRatingDisplay
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)

bool UInitScreen_C::GetRequiresRatingDisplay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetRequiresRatingDisplay");

	Params::InitScreen_C_GetRequiresRatingDisplay Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function InitScreen.InitScreen_C.GetPatchPercentage
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// float                                   ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

float UInitScreen_C::GetPatchPercentage()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetPatchPercentage");

	Params::InitScreen_C_GetPatchPercentage Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function InitScreen.InitScreen_C.SequenceEvent_0
// (Public, BlueprintCallable, BlueprintEvent)

void UInitScreen_C::SequenceEvent_0()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SequenceEvent_0");

	UObject::ProcessEvent(Func, nullptr);
}

}

