#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InspectActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass InspectActionTraits.InspectActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UInspectActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"InspectActionTraits_C">();
	}
	static class UInspectActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInspectActionTraits_C>();
	}
};
static_assert(alignof(UInspectActionTraits_C) == 0x000008, "Wrong alignment on UInspectActionTraits_C");
static_assert(sizeof(UInspectActionTraits_C) == 0x000040, "Wrong size on UInspectActionTraits_C");

}

