#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LeaveMatchConfirmationModal

#include "Basic.hpp"

#include "LeaveMatchConfirmationModal_classes.hpp"
#include "LeaveMatchConfirmationModal_parameters.hpp"


namespace SDK
{

// Function LeaveMatchConfirmationModal.LeaveMatchConfirmationModal_C.ExecuteUbergraph_LeaveMatchConfirmationModal
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULeaveMatchConfirmationModal_C::ExecuteUbergraph_LeaveMatchConfirmationModal(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_LeaveMatchConfirmationModal");

	Params::LeaveMatchConfirmationModal_C_ExecuteUbergraph_LeaveMatchConfirmationModal Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LeaveMatchConfirmationModal.LeaveMatchConfirmationModal_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULeaveMatchConfirmationModal_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LeaveMatchConfirmationModal.LeaveMatchConfirmationModal_C.Destruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULeaveMatchConfirmationModal_C::Destruct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Destruct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LeaveMatchConfirmationModal.LeaveMatchConfirmationModal_C.OnExitCanceled
// (BlueprintCallable, BlueprintEvent)

void ULeaveMatchConfirmationModal_C::OnExitCanceled()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnExitCanceled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LeaveMatchConfirmationModal.LeaveMatchConfirmationModal_C.OnExitConfirmed
// (BlueprintCallable, BlueprintEvent)

void ULeaveMatchConfirmationModal_C::OnExitConfirmed()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnExitConfirmed");

	UObject::ProcessEvent(Func, nullptr);
}

}

