#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoadingThrobberSmall

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass LoadingThrobberSmall.LoadingThrobberSmall_C
// 0x0070 (0x0308 - 0x0298)
class ULoadingThrobberSmall_C final : public UDesignableUserWidget
{
public:
	class UWidgetAnimation*                       Hover;                                             // 0x0298(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 Anchor;                                            // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackMagic;                                         // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BluredDot;                                         // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Border;                                            // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 FrontMagic;                                        // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 LeftLine;                                          // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 RightLine;                                         // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FLinearColor                           HoverColor;                                        // 0x02D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class USharedButtonText1_C* TextButton)> OnClicked;                                         // 0x02E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(class USharedButtonText1_C* TextButton)> OnHovered;                                         // 0x02F8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LoadingThrobberSmall_C">();
	}
	static class ULoadingThrobberSmall_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ULoadingThrobberSmall_C>();
	}
};
static_assert(alignof(ULoadingThrobberSmall_C) == 0x000008, "Wrong alignment on ULoadingThrobberSmall_C");
static_assert(sizeof(ULoadingThrobberSmall_C) == 0x000308, "Wrong size on ULoadingThrobberSmall_C");
static_assert(offsetof(ULoadingThrobberSmall_C, Hover) == 0x000298, "Member 'ULoadingThrobberSmall_C::Hover' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, Anchor) == 0x0002A0, "Member 'ULoadingThrobberSmall_C::Anchor' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, BackMagic) == 0x0002A8, "Member 'ULoadingThrobberSmall_C::BackMagic' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, BluredDot) == 0x0002B0, "Member 'ULoadingThrobberSmall_C::BluredDot' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, Border) == 0x0002B8, "Member 'ULoadingThrobberSmall_C::Border' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, FrontMagic) == 0x0002C0, "Member 'ULoadingThrobberSmall_C::FrontMagic' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, LeftLine) == 0x0002C8, "Member 'ULoadingThrobberSmall_C::LeftLine' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, RightLine) == 0x0002D0, "Member 'ULoadingThrobberSmall_C::RightLine' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, HoverColor) == 0x0002D8, "Member 'ULoadingThrobberSmall_C::HoverColor' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, OnClicked) == 0x0002E8, "Member 'ULoadingThrobberSmall_C::OnClicked' has a wrong offset!");
static_assert(offsetof(ULoadingThrobberSmall_C, OnHovered) == 0x0002F8, "Member 'ULoadingThrobberSmall_C::OnHovered' has a wrong offset!");

}

