#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LoginQueue

#include "Basic.hpp"

#include "LoginQueue_classes.hpp"
#include "LoginQueue_parameters.hpp"


namespace SDK
{

// Function LoginQueue.LoginQueue_C.ExecuteUbergraph_LoginQueue
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ULoginQueue_C::ExecuteUbergraph_LoginQueue(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_LoginQueue");

	Params::LoginQueue_C_ExecuteUbergraph_LoginQueue Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LoginQueue.LoginQueue_C.BndEvt__ExitButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature
// (BlueprintEvent)

void ULoginQueue_C::BndEvt__ExitButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__ExitButton_K2Node_ComponentBoundEvent_1_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginQueue.LoginQueue_C.BndEvt__LogoutButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature
// (BlueprintEvent)

void ULoginQueue_C::BndEvt__LogoutButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__LogoutButton_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginQueue.LoginQueue_C.OnLoginReady
// (BlueprintCallable, BlueprintEvent)

void ULoginQueue_C::OnLoginReady()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnLoginReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginQueue.LoginQueue_C.OnQueueUpdated
// (BlueprintCallable, BlueprintEvent)

void ULoginQueue_C::OnQueueUpdated()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnQueueUpdated");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginQueue.LoginQueue_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void ULoginQueue_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginQueue.LoginQueue_C.UpdateQueueStatus
// (Public, BlueprintCallable, BlueprintEvent)

void ULoginQueue_C::UpdateQueueStatus()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateQueueStatus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function LoginQueue.LoginQueue_C.UpdateWaitTime
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)

void ULoginQueue_C::UpdateWaitTime()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateWaitTime");

	UObject::ProcessEvent(Func, nullptr);
}

}

