#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MobileSettingsOverrides

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MobileSettingsOverrides.MobileSettingsOverrides_C
// 0x0000 (0x0170 - 0x0170)
class UMobileSettingsOverrides_C final : public UAresSettingsOverrides
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MobileSettingsOverrides_C">();
	}
	static class UMobileSettingsOverrides_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMobileSettingsOverrides_C>();
	}
};
static_assert(alignof(UMobileSettingsOverrides_C) == 0x000008, "Wrong alignment on UMobileSettingsOverrides_C");
static_assert(sizeof(UMobileSettingsOverrides_C) == 0x000170, "Wrong size on UMobileSettingsOverrides_C");

}

