#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NeedSupportPingActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NeedSupportPingActionTraits.NeedSupportPingActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UNeedSupportPingActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NeedSupportPingActionTraits_C">();
	}
	static class UNeedSupportPingActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNeedSupportPingActionTraits_C>();
	}
};
static_assert(alignof(UNeedSupportPingActionTraits_C) == 0x000008, "Wrong alignment on UNeedSupportPingActionTraits_C");
static_assert(sizeof(UNeedSupportPingActionTraits_C) == 0x000040, "Wrong size on UNeedSupportPingActionTraits_C");

}

