#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: NextWeaponActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass NextWeaponActionTraits.NextWeaponActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UNextWeaponActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"NextWeaponActionTraits_C">();
	}
	static class UNextWeaponActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UNextWeaponActionTraits_C>();
	}
};
static_assert(alignof(UNextWeaponActionTraits_C) == 0x000008, "Wrong alignment on UNextWeaponActionTraits_C");
static_assert(sizeof(UNextWeaponActionTraits_C) == 0x000040, "Wrong size on UNextWeaponActionTraits_C");

}

