#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OnMywayPingActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OnMywayPingActionTraits.OnMywayPingActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UOnMywayPingActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"OnMywayPingActionTraits_C">();
	}
	static class UOnMywayPingActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOnMywayPingActionTraits_C>();
	}
};
static_assert(alignof(UOnMywayPingActionTraits_C) == 0x000008, "Wrong alignment on UOnMywayPingActionTraits_C");
static_assert(sizeof(UOnMywayPingActionTraits_C) == 0x000040, "Wrong size on UOnMywayPingActionTraits_C");

}

