#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OpenCommTree2ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OpenCommTree2ActionTraits.OpenCommTree2ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UOpenCommTree2ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"OpenCommTree2ActionTraits_C">();
	}
	static class UOpenCommTree2ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOpenCommTree2ActionTraits_C>();
	}
};
static_assert(alignof(UOpenCommTree2ActionTraits_C) == 0x000008, "Wrong alignment on UOpenCommTree2ActionTraits_C");
static_assert(sizeof(UOpenCommTree2ActionTraits_C) == 0x000040, "Wrong size on UOpenCommTree2ActionTraits_C");

}

