#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OpenCommMenuActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OpenCommMenuActionTraits.OpenCommMenuActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UOpenCommMenuActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"OpenCommMenuActionTraits_C">();
	}
	static class UOpenCommMenuActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOpenCommMenuActionTraits_C>();
	}
};
static_assert(alignof(UOpenCommMenuActionTraits_C) == 0x000008, "Wrong alignment on UOpenCommMenuActionTraits_C");
static_assert(sizeof(UOpenCommMenuActionTraits_C) == 0x000040, "Wrong size on UOpenCommMenuActionTraits_C");

}

