#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: OpenCommTree1ActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass OpenCommTree1ActionTraits.OpenCommTree1ActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UOpenCommTree1ActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"OpenCommTree1ActionTraits_C">();
	}
	static class UOpenCommTree1ActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UOpenCommTree1ActionTraits_C>();
	}
};
static_assert(alignof(UOpenCommTree1ActionTraits_C) == 0x000008, "Wrong alignment on UOpenCommTree1ActionTraits_C");
static_assert(sizeof(UOpenCommTree1ActionTraits_C) == 0x000040, "Wrong size on UOpenCommTree1ActionTraits_C");

}

