#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PingActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PingActionTraits.PingActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UPingActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PingActionTraits_C">();
	}
	static class UPingActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPingActionTraits_C>();
	}
};
static_assert(alignof(UPingActionTraits_C) == 0x000008, "Wrong alignment on UPingActionTraits_C");
static_assert(sizeof(UPingActionTraits_C) == 0x000040, "Wrong size on UPingActionTraits_C");

}

