#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerAliasInit

#include "Basic.hpp"

#include "ShooterGame_structs.hpp"
#include "UMG_structs.hpp"
#include "EInputValidated_structs.hpp"
#include "Engine_structs.hpp"
#include "SlateCore_structs.hpp"


namespace SDK::Params
{

// Function PlayerAliasInit.PlayerAliasInit_C.ExecuteUbergraph_PlayerAliasInit
// 0x0130 (0x0130 - 0x0000)
struct PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate;              // 0x0004(0x0014)(ZeroConstructor, NoDestructor)
	TDelegate<void(EPlayerAliasError Problem)>    K2Node_CreateDelegate_OutputDelegate_1;            // 0x0018(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   K2Node_ComponentBoundEvent_Text;                   // 0x0030(0x0018)(ConstParm)
	TDelegate<void(EPlayerAliasError Problem)>    K2Node_CreateDelegate_OutputDelegate_2;            // 0x0048(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_5C[0x4];                                       // 0x005C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue;    // 0x0060(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void()>                             K2Node_CreateDelegate_OutputDelegate_3;            // 0x0068(0x0014)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_7C[0x4];                                       // 0x007C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UPlayerAliasManager*                    CallFunc_GetPlayerAliasManager_ReturnValue;        // 0x0080(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           CallFunc_K2_SetTimerDelegate_ReturnValue;          // 0x0088(0x0008)(NoDestructor, HasGetValueTypeHash)
	EPlayerAliasError                             K2Node_CustomEvent_Problem_1;                      // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EPlayerAliasError                             K2Node_CustomEvent_Problem;                        // 0x0091(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_92[0x6];                                       // 0x0092(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_Get_LocalizedErrorText_ReturnValue;       // 0x0098(0x0018)()
	class FText                                   CallFunc_Get_LocalizedErrorText_ReturnValue_1;     // 0x00B0(0x0018)()
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x00C8(0x0018)()
	class FString                                 CallFunc_Conv_TextToString_ReturnValue;            // 0x00E0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FPlayerAlias                           K2Node_MakeStruct_PlayerAlias;                     // 0x00F0(0x0020)()
	bool                                          CallFunc_CheckLocalValidation_IsValid;             // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   CallFunc_CheckLocalValidation_ValidationError;     // 0x0118(0x0018)()
};
static_assert(alignof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit) == 0x000008, "Wrong alignment on PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit");
static_assert(sizeof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit) == 0x000130, "Wrong size on PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, EntryPoint) == 0x000000, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::EntryPoint' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_CreateDelegate_OutputDelegate) == 0x000004, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_CreateDelegate_OutputDelegate_1) == 0x000018, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_ComponentBoundEvent_Text) == 0x000030, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_ComponentBoundEvent_Text' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_CreateDelegate_OutputDelegate_2) == 0x000048, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_GetAresClientGameInstance_ReturnValue) == 0x000060, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_GetAresClientGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_CreateDelegate_OutputDelegate_3) == 0x000068, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_GetPlayerAliasManager_ReturnValue) == 0x000080, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_GetPlayerAliasManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_K2_SetTimerDelegate_ReturnValue) == 0x000088, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_K2_SetTimerDelegate_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_CustomEvent_Problem_1) == 0x000090, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_CustomEvent_Problem_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_CustomEvent_Problem) == 0x000091, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_CustomEvent_Problem' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_Get_LocalizedErrorText_ReturnValue) == 0x000098, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_Get_LocalizedErrorText_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_Get_LocalizedErrorText_ReturnValue_1) == 0x0000B0, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_Get_LocalizedErrorText_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_GetText_ReturnValue) == 0x0000C8, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_Conv_TextToString_ReturnValue) == 0x0000E0, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_Conv_TextToString_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, K2Node_MakeStruct_PlayerAlias) == 0x0000F0, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::K2Node_MakeStruct_PlayerAlias' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_CheckLocalValidation_IsValid) == 0x000110, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_CheckLocalValidation_IsValid' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit, CallFunc_CheckLocalValidation_ValidationError) == 0x000118, "Member 'PlayerAliasInit_C_ExecuteUbergraph_PlayerAliasInit::CallFunc_CheckLocalValidation_ValidationError' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.OnInvalidOrError
// 0x0001 (0x0001 - 0x0000)
struct PlayerAliasInit_C_OnInvalidOrError final
{
public:
	EPlayerAliasError                             Problem;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PlayerAliasInit_C_OnInvalidOrError) == 0x000001, "Wrong alignment on PlayerAliasInit_C_OnInvalidOrError");
static_assert(sizeof(PlayerAliasInit_C_OnInvalidOrError) == 0x000001, "Wrong size on PlayerAliasInit_C_OnInvalidOrError");
static_assert(offsetof(PlayerAliasInit_C_OnInvalidOrError, Problem) == 0x000000, "Member 'PlayerAliasInit_C_OnInvalidOrError::Problem' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.OnValidationError
// 0x0001 (0x0001 - 0x0000)
struct PlayerAliasInit_C_OnValidationError final
{
public:
	EPlayerAliasError                             Problem;                                           // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PlayerAliasInit_C_OnValidationError) == 0x000001, "Wrong alignment on PlayerAliasInit_C_OnValidationError");
static_assert(sizeof(PlayerAliasInit_C_OnValidationError) == 0x000001, "Wrong size on PlayerAliasInit_C_OnValidationError");
static_assert(offsetof(PlayerAliasInit_C_OnValidationError, Problem) == 0x000000, "Member 'PlayerAliasInit_C_OnValidationError::Problem' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature
// 0x0018 (0x0018 - 0x0000)
struct PlayerAliasInit_C_BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature final
{
public:
	class FText                                   Text;                                              // 0x0000(0x0018)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
};
static_assert(alignof(PlayerAliasInit_C_BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature) == 0x000008, "Wrong alignment on PlayerAliasInit_C_BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature");
static_assert(sizeof(PlayerAliasInit_C_BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature) == 0x000018, "Wrong size on PlayerAliasInit_C_BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature");
static_assert(offsetof(PlayerAliasInit_C_BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature, Text) == 0x000000, "Member 'PlayerAliasInit_C_BndEvt__DisplayNameInput_K2Node_ComponentBoundEvent_2_OnEditableTextBoxChangedEvent__DelegateSignature::Text' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.Get_ValidationIcon_Brush_0
// 0x01B8 (0x01B8 - 0x0000)
struct PlayerAliasInit_C_Get_ValidationIcon_Brush_0 final
{
public:
	struct FSlateBrush                            ReturnValue;                                       // 0x0000(0x0090)(Parm, OutParm, ReturnParm)
	EInputValidated                               Temp_byte_Variable;                                // 0x0090(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_91[0x7];                                       // 0x0091(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FSlateBrush                            CallFunc_NoResourceBrush_ReturnValue;              // 0x0098(0x0090)()
	struct FSlateBrush                            K2Node_Select_Default;                             // 0x0128(0x0090)()
};
static_assert(alignof(PlayerAliasInit_C_Get_ValidationIcon_Brush_0) == 0x000008, "Wrong alignment on PlayerAliasInit_C_Get_ValidationIcon_Brush_0");
static_assert(sizeof(PlayerAliasInit_C_Get_ValidationIcon_Brush_0) == 0x0001B8, "Wrong size on PlayerAliasInit_C_Get_ValidationIcon_Brush_0");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationIcon_Brush_0, ReturnValue) == 0x000000, "Member 'PlayerAliasInit_C_Get_ValidationIcon_Brush_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationIcon_Brush_0, Temp_byte_Variable) == 0x000090, "Member 'PlayerAliasInit_C_Get_ValidationIcon_Brush_0::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationIcon_Brush_0, CallFunc_NoResourceBrush_ReturnValue) == 0x000098, "Member 'PlayerAliasInit_C_Get_ValidationIcon_Brush_0::CallFunc_NoResourceBrush_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationIcon_Brush_0, K2Node_Select_Default) == 0x000128, "Member 'PlayerAliasInit_C_Get_ValidationIcon_Brush_0::K2Node_Select_Default' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.Get_ValidationErrorText_Visibility_0
// 0x0028 (0x0028 - 0x0000)
struct PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0 final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EInputValidated                               Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_2;                              // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_3;                              // 0x0005(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_4;                              // 0x0006(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_5;                              // 0x0007(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class FText                                   CallFunc_GetText_ReturnValue;                      // 0x0008(0x0018)()
	bool                                          CallFunc_TextIsEmpty_ReturnValue;                  // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0021(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              K2Node_Select_Default_1;                           // 0x0022(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0) == 0x000008, "Wrong alignment on PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0");
static_assert(sizeof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0) == 0x000028, "Wrong size on PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, ReturnValue) == 0x000000, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, Temp_bool_Variable) == 0x000001, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, Temp_byte_Variable) == 0x000002, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, Temp_byte_Variable_1) == 0x000003, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, Temp_byte_Variable_2) == 0x000004, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::Temp_byte_Variable_2' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, Temp_byte_Variable_3) == 0x000005, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::Temp_byte_Variable_3' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, Temp_byte_Variable_4) == 0x000006, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::Temp_byte_Variable_4' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, Temp_byte_Variable_5) == 0x000007, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::Temp_byte_Variable_5' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, CallFunc_GetText_ReturnValue) == 0x000008, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::CallFunc_GetText_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, CallFunc_TextIsEmpty_ReturnValue) == 0x000020, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::CallFunc_TextIsEmpty_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, K2Node_Select_Default) == 0x000021, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::K2Node_Select_Default' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0, K2Node_Select_Default_1) == 0x000022, "Member 'PlayerAliasInit_C_Get_ValidationErrorText_Visibility_0::K2Node_Select_Default_1' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.Get_ConfirmButtonEnabled
// 0x0002 (0x0002 - 0x0000)
struct PlayerAliasInit_C_Get_ConfirmButtonEnabled final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PlayerAliasInit_C_Get_ConfirmButtonEnabled) == 0x000001, "Wrong alignment on PlayerAliasInit_C_Get_ConfirmButtonEnabled");
static_assert(sizeof(PlayerAliasInit_C_Get_ConfirmButtonEnabled) == 0x000002, "Wrong size on PlayerAliasInit_C_Get_ConfirmButtonEnabled");
static_assert(offsetof(PlayerAliasInit_C_Get_ConfirmButtonEnabled, ReturnValue) == 0x000000, "Member 'PlayerAliasInit_C_Get_ConfirmButtonEnabled::ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_ConfirmButtonEnabled, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000001, "Member 'PlayerAliasInit_C_Get_ConfirmButtonEnabled::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.Get_LocalizedErrorText
// 0x00B8 (0x00B8 - 0x0000)
struct PlayerAliasInit_C_Get_LocalizedErrorText final
{
public:
	EPlayerAliasError                             PlayerAliasError;                                  // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   ReturnValue;                                       // 0x0008(0x0018)(Parm, OutParm, ReturnParm)
	EPlayerAliasError                             Temp_byte_Variable;                                // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   Temp_text_Variable;                                // 0x0028(0x0018)()
	class FText                                   Temp_text_Variable_1;                              // 0x0040(0x0018)()
	class FText                                   Temp_text_Variable_2;                              // 0x0058(0x0018)()
	class FText                                   Temp_text_Variable_3;                              // 0x0070(0x0018)()
	class FText                                   Temp_text_Variable_4;                              // 0x0088(0x0018)()
	class FText                                   K2Node_Select_Default;                             // 0x00A0(0x0018)()
};
static_assert(alignof(PlayerAliasInit_C_Get_LocalizedErrorText) == 0x000008, "Wrong alignment on PlayerAliasInit_C_Get_LocalizedErrorText");
static_assert(sizeof(PlayerAliasInit_C_Get_LocalizedErrorText) == 0x0000B8, "Wrong size on PlayerAliasInit_C_Get_LocalizedErrorText");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, PlayerAliasError) == 0x000000, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::PlayerAliasError' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, ReturnValue) == 0x000008, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, Temp_byte_Variable) == 0x000020, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, Temp_text_Variable) == 0x000028, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::Temp_text_Variable' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, Temp_text_Variable_1) == 0x000040, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::Temp_text_Variable_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, Temp_text_Variable_2) == 0x000058, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::Temp_text_Variable_2' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, Temp_text_Variable_3) == 0x000070, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::Temp_text_Variable_3' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, Temp_text_Variable_4) == 0x000088, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::Temp_text_Variable_4' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_LocalizedErrorText, K2Node_Select_Default) == 0x0000A0, "Member 'PlayerAliasInit_C_Get_LocalizedErrorText::K2Node_Select_Default' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.Get_TagLineInput_Visibility_0
// 0x0020 (0x0020 - 0x0000)
struct PlayerAliasInit_C_Get_TagLineInput_Visibility_0 final
{
public:
	ESlateVisibility                              ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Temp_bool_Variable;                                // 0x0001(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              Temp_byte_Variable;                                // 0x0002(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ESlateVisibility                              Temp_byte_Variable_1;                              // 0x0003(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue;    // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayerAliasManager*                    CallFunc_GetPlayerAliasManager_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanSetTagLine_ReturnValue;                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	ESlateVisibility                              K2Node_Select_Default;                             // 0x0019(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0) == 0x000008, "Wrong alignment on PlayerAliasInit_C_Get_TagLineInput_Visibility_0");
static_assert(sizeof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0) == 0x000020, "Wrong size on PlayerAliasInit_C_Get_TagLineInput_Visibility_0");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, ReturnValue) == 0x000000, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, Temp_bool_Variable) == 0x000001, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::Temp_bool_Variable' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, Temp_byte_Variable) == 0x000002, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, Temp_byte_Variable_1) == 0x000003, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::Temp_byte_Variable_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, CallFunc_GetAresClientGameInstance_ReturnValue) == 0x000008, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::CallFunc_GetAresClientGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, CallFunc_GetPlayerAliasManager_ReturnValue) == 0x000010, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::CallFunc_GetPlayerAliasManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, CallFunc_CanSetTagLine_ReturnValue) == 0x000018, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::CallFunc_CanSetTagLine_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_Visibility_0, K2Node_Select_Default) == 0x000019, "Member 'PlayerAliasInit_C_Get_TagLineInput_Visibility_0::K2Node_Select_Default' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.CheckLocalValidation
// 0x0050 (0x0050 - 0x0000)
struct PlayerAliasInit_C_CheckLocalValidation final
{
public:
	struct FPlayerAlias                           PlayerAlias;                                       // 0x0000(0x0020)(BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
	bool                                          IsValid;                                           // 0x0020(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x7];                                       // 0x0021(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FText                                   ValidationError;                                   // 0x0028(0x0018)(Parm, OutParm)
	bool                                          NewLocalVar_0;                                     // 0x0040(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_41[0x3];                                       // 0x0041(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Len_ReturnValue;                          // 0x0044(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Len_ReturnValue_1;                        // 0x0048(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_IntInt_ReturnValue;               // 0x004C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Greater_IntInt_ReturnValue_1;             // 0x004D(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_Less_IntInt_ReturnValue;                  // 0x004E(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PlayerAliasInit_C_CheckLocalValidation) == 0x000008, "Wrong alignment on PlayerAliasInit_C_CheckLocalValidation");
static_assert(sizeof(PlayerAliasInit_C_CheckLocalValidation) == 0x000050, "Wrong size on PlayerAliasInit_C_CheckLocalValidation");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, PlayerAlias) == 0x000000, "Member 'PlayerAliasInit_C_CheckLocalValidation::PlayerAlias' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, IsValid) == 0x000020, "Member 'PlayerAliasInit_C_CheckLocalValidation::IsValid' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, ValidationError) == 0x000028, "Member 'PlayerAliasInit_C_CheckLocalValidation::ValidationError' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, NewLocalVar_0) == 0x000040, "Member 'PlayerAliasInit_C_CheckLocalValidation::NewLocalVar_0' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, CallFunc_Len_ReturnValue) == 0x000044, "Member 'PlayerAliasInit_C_CheckLocalValidation::CallFunc_Len_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, CallFunc_Len_ReturnValue_1) == 0x000048, "Member 'PlayerAliasInit_C_CheckLocalValidation::CallFunc_Len_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, CallFunc_Greater_IntInt_ReturnValue) == 0x00004C, "Member 'PlayerAliasInit_C_CheckLocalValidation::CallFunc_Greater_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, CallFunc_Greater_IntInt_ReturnValue_1) == 0x00004D, "Member 'PlayerAliasInit_C_CheckLocalValidation::CallFunc_Greater_IntInt_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_CheckLocalValidation, CallFunc_Less_IntInt_ReturnValue) == 0x00004E, "Member 'PlayerAliasInit_C_CheckLocalValidation::CallFunc_Less_IntInt_ReturnValue' has a wrong offset!");

// Function PlayerAliasInit.PlayerAliasInit_C.Get_TagLineInput_bIsEnabled_0
// 0x0020 (0x0020 - 0x0000)
struct PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0 final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAresClientGameInstance*                CallFunc_GetAresClientGameInstance_ReturnValue;    // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPlayerAliasManager*                    CallFunc_GetPlayerAliasManager_ReturnValue;        // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_CanSetTagLine_ReturnValue;                // 0x0018(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0) == 0x000008, "Wrong alignment on PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0");
static_assert(sizeof(PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0) == 0x000020, "Wrong size on PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0, ReturnValue) == 0x000000, "Member 'PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0::ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0, CallFunc_GetAresClientGameInstance_ReturnValue) == 0x000008, "Member 'PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0::CallFunc_GetAresClientGameInstance_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0, CallFunc_GetPlayerAliasManager_ReturnValue) == 0x000010, "Member 'PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0::CallFunc_GetPlayerAliasManager_ReturnValue' has a wrong offset!");
static_assert(offsetof(PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0, CallFunc_CanSetTagLine_ReturnValue) == 0x000018, "Member 'PlayerAliasInit_C_Get_TagLineInput_bIsEnabled_0::CallFunc_CanSetTagLine_ReturnValue' has a wrong offset!");

}

