#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerFeedbackToolModule

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "PlayerFeedbackToolModule_structs.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class PlayerFeedbackToolModule.PlayerFeedbackToolFunctionLibrary
// 0x0000 (0x0030 - 0x0030)
class UPlayerFeedbackToolFunctionLibrary final : public UBlueprintFunctionLibrary
{
public:
	static class UPlayerFeedbackToolManager* GetPlayerFeedbackToolManager();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlayerFeedbackToolFunctionLibrary">();
	}
	static class UPlayerFeedbackToolFunctionLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerFeedbackToolFunctionLibrary>();
	}
};
static_assert(alignof(UPlayerFeedbackToolFunctionLibrary) == 0x000008, "Wrong alignment on UPlayerFeedbackToolFunctionLibrary");
static_assert(sizeof(UPlayerFeedbackToolFunctionLibrary) == 0x000030, "Wrong size on UPlayerFeedbackToolFunctionLibrary");

// Class PlayerFeedbackToolModule.PlayerFeedbackToolManager
// 0x00E0 (0x0110 - 0x0030)
class alignas(0x10) UPlayerFeedbackToolManager final : public UObject
{
public:
	TMulticastInlineDelegate<void(struct FPlayerFeedbackSurvey& survey)> OnSurveyReceivedEvent;                             // 0x0030(0x0010)(ZeroConstructor, InstancedReference, BlueprintAssignable, NativeAccessSpecifierPublic)
	uint8                                         Pad_40[0xD0];                                      // 0x0040(0x00D0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static void RequestSurveyForEvent(class UPlayerFeedbackToolManager* pftManager, const class FString& eventType, class UProperty* anyStruct);

	void AddExpandedSurveyAction();
	void AddMetadataField(const class FString& key, const class FString& value);
	void RequestSurvey(const class FString& eventType);
	void SendSurveyResults(bool didOptOutOfSurvey);
	void SetQuestionResponse(int32 questionID, const class FString& key, const class FString& value);

	const struct FPlayerFeedbackSurvey GetActiveSurvey() const;
	bool HasActiveSurvey() const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlayerFeedbackToolManager">();
	}
	static class UPlayerFeedbackToolManager* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerFeedbackToolManager>();
	}
};
static_assert(alignof(UPlayerFeedbackToolManager) == 0x000010, "Wrong alignment on UPlayerFeedbackToolManager");
static_assert(sizeof(UPlayerFeedbackToolManager) == 0x000110, "Wrong size on UPlayerFeedbackToolManager");
static_assert(offsetof(UPlayerFeedbackToolManager, OnSurveyReceivedEvent) == 0x000030, "Member 'UPlayerFeedbackToolManager::OnSurveyReceivedEvent' has a wrong offset!");

}

