#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlaytimeManagerWidgetBP

#include "Basic.hpp"

#include "PlaytimeManagerWidgetBP_classes.hpp"
#include "PlaytimeManagerWidgetBP_parameters.hpp"


namespace SDK
{

// Function PlaytimeManagerWidgetBP.PlaytimeManagerWidgetBP_C.ExecuteUbergraph_PlaytimeManagerWidgetBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlaytimeManagerWidgetBP_C::ExecuteUbergraph_PlaytimeManagerWidgetBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_PlaytimeManagerWidgetBP");

	Params::PlaytimeManagerWidgetBP_C_ExecuteUbergraph_PlaytimeManagerWidgetBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlaytimeManagerWidgetBP.PlaytimeManagerWidgetBP_C.HandleSessionLoopStateChanged
// (BlueprintCallable, BlueprintEvent)

void UPlaytimeManagerWidgetBP_C::HandleSessionLoopStateChanged()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleSessionLoopStateChanged");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlaytimeManagerWidgetBP.PlaytimeManagerWidgetBP_C.BndEvt__NotificationCloseButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void UPlaytimeManagerWidgetBP_C::BndEvt__NotificationCloseButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__NotificationCloseButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlaytimeManagerWidgetBP.PlaytimeManagerWidgetBP_C.HandlePlaytimeNotification
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Notification                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
// int32                                   Minutes                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UPlaytimeManagerWidgetBP_C::HandlePlaytimeNotification(const class FString& Notification, int32 Minutes)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandlePlaytimeNotification");

	Params::PlaytimeManagerWidgetBP_C_HandlePlaytimeNotification Parms{};

	Parms.Notification = std::move(Notification);
	Parms.Minutes = Minutes;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlaytimeManagerWidgetBP.PlaytimeManagerWidgetBP_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UPlaytimeManagerWidgetBP_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlaytimeManagerWidgetBP.PlaytimeManagerWidgetBP_C.UpdateCursorHelpTextVisibility
// (Public, BlueprintCallable, BlueprintEvent)

void UPlaytimeManagerWidgetBP_C::UpdateCursorHelpTextVisibility()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateCursorHelpTextVisibility");

	UObject::ProcessEvent(Func, nullptr);
}

}

