#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerFeedbackToolModule

#include "Basic.hpp"

#include "PlayerFeedbackToolModule_classes.hpp"
#include "PlayerFeedbackToolModule_parameters.hpp"


namespace SDK
{

// Function PlayerFeedbackToolModule.PlayerFeedbackToolFunctionLibrary.GetPlayerFeedbackToolManager
// (Final, Native, Static, Public, BlueprintCallable, BlueprintPure)
// Parameters:
// class UPlayerFeedbackToolManager*       ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

class UPlayerFeedbackToolManager* UPlayerFeedbackToolFunctionLibrary::GetPlayerFeedbackToolManager()
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("GetPlayerFeedbackToolManager");

	Params::PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager Parms{};

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.RequestSurveyForEvent
// (Final, Native, Static, Public, BlueprintCallable)
// Parameters:
// class UPlayerFeedbackToolManager*       pftManager                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           eventType                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class UProperty*                        anyStruct                                              (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerFeedbackToolManager::RequestSurveyForEvent(class UPlayerFeedbackToolManager* pftManager, const class FString& eventType, class UProperty* anyStruct)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("RequestSurveyForEvent");

	Params::PlayerFeedbackToolManager_RequestSurveyForEvent Parms{};

	Parms.pftManager = pftManager;
	Parms.eventType = std::move(eventType);
	Parms.anyStruct = anyStruct;

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.AddExpandedSurveyAction
// (Final, Native, Public, BlueprintCallable)

void UPlayerFeedbackToolManager::AddExpandedSurveyAction()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AddExpandedSurveyAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.AddMetadataField
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerFeedbackToolManager::AddMetadataField(const class FString& key, const class FString& value)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AddMetadataField");

	Params::PlayerFeedbackToolManager_AddMetadataField Parms{};

	Parms.key = std::move(key);
	Parms.value = std::move(value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.RequestSurvey
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// class FString                           eventType                                              (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerFeedbackToolManager::RequestSurvey(const class FString& eventType)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RequestSurvey");

	Params::PlayerFeedbackToolManager_RequestSurvey Parms{};

	Parms.eventType = std::move(eventType);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.SendSurveyResults
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// bool                                    didOptOutOfSurvey                                      (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerFeedbackToolManager::SendSurveyResults(bool didOptOutOfSurvey)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SendSurveyResults");

	Params::PlayerFeedbackToolManager_SendSurveyResults Parms{};

	Parms.didOptOutOfSurvey = didOptOutOfSurvey;

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.SetQuestionResponse
// (Final, Native, Public, BlueprintCallable)
// Parameters:
// int32                                   questionID                                             (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           key                                                    (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// class FString                           value                                                  (Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UPlayerFeedbackToolManager::SetQuestionResponse(int32 questionID, const class FString& key, const class FString& value)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetQuestionResponse");

	Params::PlayerFeedbackToolManager_SetQuestionResponse Parms{};

	Parms.questionID = questionID;
	Parms.key = std::move(key);
	Parms.value = std::move(value);

	UObject::ProcessEvent(Func, &Parms);
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.GetActiveSurvey
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// const struct FPlayerFeedbackSurvey      ReturnValue                                            (ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)

const struct FPlayerFeedbackSurvey UPlayerFeedbackToolManager::GetActiveSurvey() const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetActiveSurvey");

	Params::PlayerFeedbackToolManager_GetActiveSurvey Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.HasActiveSurvey
// (Final, Native, Public, BlueprintCallable, BlueprintPure, Const)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

bool UPlayerFeedbackToolManager::HasActiveSurvey() const
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HasActiveSurvey");

	Params::PlayerFeedbackToolManager_HasActiveSurvey Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

