#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlaytimeManagerWidgetBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "ShooterGame_structs.hpp"
#include "ShooterGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlaytimeManagerWidgetBP.PlaytimeManagerWidgetBP_C
// 0x0038 (0x02D0 - 0x0298)
class UPlaytimeManagerWidgetBP_C final : public UCrossWorldUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 CloseImage;                                        // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             CursorHelperText;                                  // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UBorder*                                NotificationBorder;                                // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           NotificationBox;                                   // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                NotificationCloseButton;                           // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             NotificationText;                                  // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_PlaytimeManagerWidgetBP(int32 EntryPoint);
	void HandleSessionLoopStateChanged();
	void BndEvt__NotificationCloseButton_K2Node_ComponentBoundEvent_20_OnButtonClickedEvent__DelegateSignature();
	void HandlePlaytimeNotification(const class FString& Notification, int32 Minutes);
	void Construct();
	void UpdateCursorHelpTextVisibility();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlaytimeManagerWidgetBP_C">();
	}
	static class UPlaytimeManagerWidgetBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlaytimeManagerWidgetBP_C>();
	}
};
static_assert(alignof(UPlaytimeManagerWidgetBP_C) == 0x000008, "Wrong alignment on UPlaytimeManagerWidgetBP_C");
static_assert(sizeof(UPlaytimeManagerWidgetBP_C) == 0x0002D0, "Wrong size on UPlaytimeManagerWidgetBP_C");
static_assert(offsetof(UPlaytimeManagerWidgetBP_C, UberGraphFrame) == 0x000298, "Member 'UPlaytimeManagerWidgetBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UPlaytimeManagerWidgetBP_C, CloseImage) == 0x0002A0, "Member 'UPlaytimeManagerWidgetBP_C::CloseImage' has a wrong offset!");
static_assert(offsetof(UPlaytimeManagerWidgetBP_C, CursorHelperText) == 0x0002A8, "Member 'UPlaytimeManagerWidgetBP_C::CursorHelperText' has a wrong offset!");
static_assert(offsetof(UPlaytimeManagerWidgetBP_C, NotificationBorder) == 0x0002B0, "Member 'UPlaytimeManagerWidgetBP_C::NotificationBorder' has a wrong offset!");
static_assert(offsetof(UPlaytimeManagerWidgetBP_C, NotificationBox) == 0x0002B8, "Member 'UPlaytimeManagerWidgetBP_C::NotificationBox' has a wrong offset!");
static_assert(offsetof(UPlaytimeManagerWidgetBP_C, NotificationCloseButton) == 0x0002C0, "Member 'UPlaytimeManagerWidgetBP_C::NotificationCloseButton' has a wrong offset!");
static_assert(offsetof(UPlaytimeManagerWidgetBP_C, NotificationText) == 0x0002C8, "Member 'UPlaytimeManagerWidgetBP_C::NotificationText' has a wrong offset!");

}

