#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerFeedbackToolModule

#include "Basic.hpp"

#include "PlayerFeedbackToolModule_structs.hpp"


namespace SDK::Params
{

// Function PlayerFeedbackToolModule.PlayerFeedbackToolFunctionLibrary.GetPlayerFeedbackToolManager
// 0x0008 (0x0008 - 0x0000)
struct PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager final
{
public:
	class UPlayerFeedbackToolManager*             ReturnValue;                                       // 0x0000(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager) == 0x000008, "Wrong alignment on PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager");
static_assert(sizeof(PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager) == 0x000008, "Wrong size on PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager");
static_assert(offsetof(PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager, ReturnValue) == 0x000000, "Member 'PlayerFeedbackToolFunctionLibrary_GetPlayerFeedbackToolManager::ReturnValue' has a wrong offset!");

// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.RequestSurveyForEvent
// 0x0020 (0x0020 - 0x0000)
struct PlayerFeedbackToolManager_RequestSurveyForEvent final
{
public:
	class UPlayerFeedbackToolManager*             pftManager;                                        // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 eventType;                                         // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class UProperty*                              anyStruct;                                         // 0x0018(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolManager_RequestSurveyForEvent) == 0x000008, "Wrong alignment on PlayerFeedbackToolManager_RequestSurveyForEvent");
static_assert(sizeof(PlayerFeedbackToolManager_RequestSurveyForEvent) == 0x000020, "Wrong size on PlayerFeedbackToolManager_RequestSurveyForEvent");
static_assert(offsetof(PlayerFeedbackToolManager_RequestSurveyForEvent, pftManager) == 0x000000, "Member 'PlayerFeedbackToolManager_RequestSurveyForEvent::pftManager' has a wrong offset!");
static_assert(offsetof(PlayerFeedbackToolManager_RequestSurveyForEvent, eventType) == 0x000008, "Member 'PlayerFeedbackToolManager_RequestSurveyForEvent::eventType' has a wrong offset!");
static_assert(offsetof(PlayerFeedbackToolManager_RequestSurveyForEvent, anyStruct) == 0x000018, "Member 'PlayerFeedbackToolManager_RequestSurveyForEvent::anyStruct' has a wrong offset!");

// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.AddMetadataField
// 0x0020 (0x0020 - 0x0000)
struct PlayerFeedbackToolManager_AddMetadataField final
{
public:
	class FString                                 key;                                               // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 value;                                             // 0x0010(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolManager_AddMetadataField) == 0x000008, "Wrong alignment on PlayerFeedbackToolManager_AddMetadataField");
static_assert(sizeof(PlayerFeedbackToolManager_AddMetadataField) == 0x000020, "Wrong size on PlayerFeedbackToolManager_AddMetadataField");
static_assert(offsetof(PlayerFeedbackToolManager_AddMetadataField, key) == 0x000000, "Member 'PlayerFeedbackToolManager_AddMetadataField::key' has a wrong offset!");
static_assert(offsetof(PlayerFeedbackToolManager_AddMetadataField, value) == 0x000010, "Member 'PlayerFeedbackToolManager_AddMetadataField::value' has a wrong offset!");

// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.RequestSurvey
// 0x0010 (0x0010 - 0x0000)
struct PlayerFeedbackToolManager_RequestSurvey final
{
public:
	class FString                                 eventType;                                         // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolManager_RequestSurvey) == 0x000008, "Wrong alignment on PlayerFeedbackToolManager_RequestSurvey");
static_assert(sizeof(PlayerFeedbackToolManager_RequestSurvey) == 0x000010, "Wrong size on PlayerFeedbackToolManager_RequestSurvey");
static_assert(offsetof(PlayerFeedbackToolManager_RequestSurvey, eventType) == 0x000000, "Member 'PlayerFeedbackToolManager_RequestSurvey::eventType' has a wrong offset!");

// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.SendSurveyResults
// 0x0001 (0x0001 - 0x0000)
struct PlayerFeedbackToolManager_SendSurveyResults final
{
public:
	bool                                          didOptOutOfSurvey;                                 // 0x0000(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolManager_SendSurveyResults) == 0x000001, "Wrong alignment on PlayerFeedbackToolManager_SendSurveyResults");
static_assert(sizeof(PlayerFeedbackToolManager_SendSurveyResults) == 0x000001, "Wrong size on PlayerFeedbackToolManager_SendSurveyResults");
static_assert(offsetof(PlayerFeedbackToolManager_SendSurveyResults, didOptOutOfSurvey) == 0x000000, "Member 'PlayerFeedbackToolManager_SendSurveyResults::didOptOutOfSurvey' has a wrong offset!");

// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.SetQuestionResponse
// 0x0028 (0x0028 - 0x0000)
struct PlayerFeedbackToolManager_SetQuestionResponse final
{
public:
	int32                                         questionID;                                        // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 key;                                               // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 value;                                             // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolManager_SetQuestionResponse) == 0x000008, "Wrong alignment on PlayerFeedbackToolManager_SetQuestionResponse");
static_assert(sizeof(PlayerFeedbackToolManager_SetQuestionResponse) == 0x000028, "Wrong size on PlayerFeedbackToolManager_SetQuestionResponse");
static_assert(offsetof(PlayerFeedbackToolManager_SetQuestionResponse, questionID) == 0x000000, "Member 'PlayerFeedbackToolManager_SetQuestionResponse::questionID' has a wrong offset!");
static_assert(offsetof(PlayerFeedbackToolManager_SetQuestionResponse, key) == 0x000008, "Member 'PlayerFeedbackToolManager_SetQuestionResponse::key' has a wrong offset!");
static_assert(offsetof(PlayerFeedbackToolManager_SetQuestionResponse, value) == 0x000018, "Member 'PlayerFeedbackToolManager_SetQuestionResponse::value' has a wrong offset!");

// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.GetActiveSurvey
// 0x0068 (0x0068 - 0x0000)
struct PlayerFeedbackToolManager_GetActiveSurvey final
{
public:
	struct FPlayerFeedbackSurvey                  ReturnValue;                                       // 0x0000(0x0068)(ConstParm, Parm, OutParm, ReturnParm, ReferenceParm, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolManager_GetActiveSurvey) == 0x000008, "Wrong alignment on PlayerFeedbackToolManager_GetActiveSurvey");
static_assert(sizeof(PlayerFeedbackToolManager_GetActiveSurvey) == 0x000068, "Wrong size on PlayerFeedbackToolManager_GetActiveSurvey");
static_assert(offsetof(PlayerFeedbackToolManager_GetActiveSurvey, ReturnValue) == 0x000000, "Member 'PlayerFeedbackToolManager_GetActiveSurvey::ReturnValue' has a wrong offset!");

// Function PlayerFeedbackToolModule.PlayerFeedbackToolManager.HasActiveSurvey
// 0x0001 (0x0001 - 0x0000)
struct PlayerFeedbackToolManager_HasActiveSurvey final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(PlayerFeedbackToolManager_HasActiveSurvey) == 0x000001, "Wrong alignment on PlayerFeedbackToolManager_HasActiveSurvey");
static_assert(sizeof(PlayerFeedbackToolManager_HasActiveSurvey) == 0x000001, "Wrong size on PlayerFeedbackToolManager_HasActiveSurvey");
static_assert(offsetof(PlayerFeedbackToolManager_HasActiveSurvey, ReturnValue) == 0x000000, "Member 'PlayerFeedbackToolManager_HasActiveSurvey::ReturnValue' has a wrong offset!");

}

