#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PrevWeaponActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass PrevWeaponActionTraits.PrevWeaponActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UPrevWeaponActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PrevWeaponActionTraits_C">();
	}
	static class UPrevWeaponActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPrevWeaponActionTraits_C>();
	}
};
static_assert(alignof(UPrevWeaponActionTraits_C) == 0x000008, "Wrong alignment on UPrevWeaponActionTraits_C");
static_assert(sizeof(UPrevWeaponActionTraits_C) == 0x000040, "Wrong size on UPrevWeaponActionTraits_C");

}

