#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Renderer

#include "Basic.hpp"

#include "Renderer_classes.hpp"
#include "Renderer_parameters.hpp"


namespace SDK
{

// Function Renderer.AresOutlineRendering.SetOutlineColorsForRender
// (Final, Native, Static, Public, HasOutParams, HasDefaults, BlueprintCallable)
// Parameters:
// class UObject*                          WorldContextObject                                     (Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FLinearColor                     AllyColor                                              (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
// struct FLinearColor                     EnemyColor                                             (ConstParm, Parm, OutParm, ZeroConstructor, ReferenceParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)

void UAresOutlineRendering::SetOutlineColorsForRender(class UObject* WorldContextObject, const struct FLinearColor& AllyColor, const struct FLinearColor& EnemyColor)
{
	static class UFunction* Func = nullptr;
	class UClass* StaticClss = StaticClass();

	if (Func == nullptr)
		Func = StaticClss->FindFunction("SetOutlineColorsForRender");

	Params::AresOutlineRendering_SetOutlineColorsForRender Parms{};

	Parms.WorldContextObject = WorldContextObject;
	Parms.AllyColor = std::move(AllyColor);
	Parms.EnemyColor = std::move(EnemyColor);

	StaticClss->DefaultObject->ProcessEvent(Func, &Parms);
}

}

