#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RiotLoginWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass RiotLoginWidget.RiotLoginWidget_C
// 0x0048 (0x02E0 - 0x0298)
class URiotLoginWidget_C final : public UUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UEditableTextBox*                       Password;                                          // 0x02A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USharedButtonMaster_C*                  SharedButtonMaster;                                // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UEditableTextBox*                       Username;                                          // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 DisplayName;                                       // 0x02B8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	class FString                                 PlayerGUID;                                        // 0x02C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          Team;                                              // 0x02D8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void ExecuteUbergraph_RiotLoginWidget(int32 EntryPoint);
	void BndEvt__Address_K2Node_ComponentBoundEvent_104_OnEditableTextChangedEvent__DelegateSignature(const class FText& Text);
	void BndEvt__Port_K2Node_ComponentBoundEvent_98_OnEditableTextChangedEvent__DelegateSignature(const class FText& Text);
	void BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"RiotLoginWidget_C">();
	}
	static class URiotLoginWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<URiotLoginWidget_C>();
	}
};
static_assert(alignof(URiotLoginWidget_C) == 0x000008, "Wrong alignment on URiotLoginWidget_C");
static_assert(sizeof(URiotLoginWidget_C) == 0x0002E0, "Wrong size on URiotLoginWidget_C");
static_assert(offsetof(URiotLoginWidget_C, UberGraphFrame) == 0x000298, "Member 'URiotLoginWidget_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(URiotLoginWidget_C, Password) == 0x0002A0, "Member 'URiotLoginWidget_C::Password' has a wrong offset!");
static_assert(offsetof(URiotLoginWidget_C, SharedButtonMaster) == 0x0002A8, "Member 'URiotLoginWidget_C::SharedButtonMaster' has a wrong offset!");
static_assert(offsetof(URiotLoginWidget_C, Username) == 0x0002B0, "Member 'URiotLoginWidget_C::Username' has a wrong offset!");
static_assert(offsetof(URiotLoginWidget_C, DisplayName) == 0x0002B8, "Member 'URiotLoginWidget_C::DisplayName' has a wrong offset!");
static_assert(offsetof(URiotLoginWidget_C, PlayerGUID) == 0x0002C8, "Member 'URiotLoginWidget_C::PlayerGUID' has a wrong offset!");
static_assert(offsetof(URiotLoginWidget_C, Team) == 0x0002D8, "Member 'URiotLoginWidget_C::Team' has a wrong offset!");

}

