#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RiotJiraSubmitter

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class RiotJiraSubmitter.RiotJiraSubmitterLibrary
// 0x0000 (0x0030 - 0x0030)
class URiotJiraSubmitterLibrary final : public UBlueprintFunctionLibrary
{
public:
	static void SubmitJiraIssue(const class UObject* WorldContextObject, const class FString& Summary, const class FString& Type, const class FString& Description, bool bIncludeScreenshot);
	static void SubmitJiraIssueLatent(class UObject* WorldContextObject, const struct FLatentActionInfo& LatentInfo, class FString* OutIssueId, const class FString& Summary, const class FString& Type, const class FString& Description, bool bIncludeScreenshot);

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"RiotJiraSubmitterLibrary">();
	}
	static class URiotJiraSubmitterLibrary* GetDefaultObj()
	{
		return GetDefaultObjImpl<URiotJiraSubmitterLibrary>();
	}
};
static_assert(alignof(URiotJiraSubmitterLibrary) == 0x000008, "Wrong alignment on URiotJiraSubmitterLibrary");
static_assert(sizeof(URiotJiraSubmitterLibrary) == 0x000030, "Wrong size on URiotJiraSubmitterLibrary");

}

