#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RiotNoFieldsLoginWidget

#include "Basic.hpp"

#include "RiotNoFieldsLoginWidget_classes.hpp"
#include "RiotNoFieldsLoginWidget_parameters.hpp"


namespace SDK
{

// Function RiotNoFieldsLoginWidget.RiotNoFieldsLoginWidget_C.ExecuteUbergraph_RiotNoFieldsLoginWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void URiotNoFieldsLoginWidget_C::ExecuteUbergraph_RiotNoFieldsLoginWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_RiotNoFieldsLoginWidget");

	Params::RiotNoFieldsLoginWidget_C_ExecuteUbergraph_RiotNoFieldsLoginWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function RiotNoFieldsLoginWidget.RiotNoFieldsLoginWidget_C.BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature
// (BlueprintEvent)

void URiotNoFieldsLoginWidget_C::BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__SharedButtonMaster_K2Node_ComponentBoundEvent_0_Clicked__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}

}

