#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: RiotJiraSubmitter

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function RiotJiraSubmitter.RiotJiraSubmitterLibrary.SubmitJiraIssue
// 0x0040 (0x0040 - 0x0000)
struct RiotJiraSubmitterLibrary_SubmitJiraIssue final
{
public:
	const class UObject*                          WorldContextObject;                                // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Summary;                                           // 0x0008(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Type;                                              // 0x0018(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Description;                                       // 0x0028(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeScreenshot;                                // 0x0038(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_39[0x7];                                       // 0x0039(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(RiotJiraSubmitterLibrary_SubmitJiraIssue) == 0x000008, "Wrong alignment on RiotJiraSubmitterLibrary_SubmitJiraIssue");
static_assert(sizeof(RiotJiraSubmitterLibrary_SubmitJiraIssue) == 0x000040, "Wrong size on RiotJiraSubmitterLibrary_SubmitJiraIssue");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssue, WorldContextObject) == 0x000000, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssue::WorldContextObject' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssue, Summary) == 0x000008, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssue::Summary' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssue, Type) == 0x000018, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssue::Type' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssue, Description) == 0x000028, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssue::Description' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssue, bIncludeScreenshot) == 0x000038, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssue::bIncludeScreenshot' has a wrong offset!");

// Function RiotJiraSubmitter.RiotJiraSubmitterLibrary.SubmitJiraIssueLatent
// 0x0070 (0x0070 - 0x0000)
struct RiotJiraSubmitterLibrary_SubmitJiraIssueLatent final
{
public:
	class UObject*                                WorldContextObject;                                // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	struct FLatentActionInfo                      LatentInfo;                                        // 0x0008(0x0020)(Parm, NoDestructor, NativeAccessSpecifierPublic)
	class FString                                 OutIssueId;                                        // 0x0028(0x0010)(Parm, OutParm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Summary;                                           // 0x0038(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Type;                                              // 0x0048(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	class FString                                 Description;                                       // 0x0058(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	bool                                          bIncludeScreenshot;                                // 0x0068(0x0001)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_69[0x7];                                       // 0x0069(0x0007)(Fixing Struct Size After Last Property [ Dumper-7 ])
};
static_assert(alignof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent) == 0x000008, "Wrong alignment on RiotJiraSubmitterLibrary_SubmitJiraIssueLatent");
static_assert(sizeof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent) == 0x000070, "Wrong size on RiotJiraSubmitterLibrary_SubmitJiraIssueLatent");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent, WorldContextObject) == 0x000000, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssueLatent::WorldContextObject' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent, LatentInfo) == 0x000008, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssueLatent::LatentInfo' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent, OutIssueId) == 0x000028, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssueLatent::OutIssueId' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent, Summary) == 0x000038, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssueLatent::Summary' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent, Type) == 0x000048, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssueLatent::Type' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent, Description) == 0x000058, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssueLatent::Description' has a wrong offset!");
static_assert(offsetof(RiotJiraSubmitterLibrary_SubmitJiraIssueLatent, bIncludeScreenshot) == 0x000068, "Member 'RiotJiraSubmitterLibrary_SubmitJiraIssueLatent::bIncludeScreenshot' has a wrong offset!");

}

