#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SecondaryTriggerActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SecondaryTriggerActionTraits.SecondaryTriggerActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class USecondaryTriggerActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SecondaryTriggerActionTraits_C">();
	}
	static class USecondaryTriggerActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USecondaryTriggerActionTraits_C>();
	}
};
static_assert(alignof(USecondaryTriggerActionTraits_C) == 0x000008, "Wrong alignment on USecondaryTriggerActionTraits_C");
static_assert(sizeof(USecondaryTriggerActionTraits_C) == 0x000040, "Wrong size on USecondaryTriggerActionTraits_C");

}

