#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SharedBackButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "UMG_structs.hpp"
#include "SharedBackButtonTypes_structs.hpp"
#include "ShooterGame_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SharedBackButton.SharedBackButton_C
// 0x00D8 (0x0370 - 0x0298)
class USharedBackButton_C final : public UDesignableUserWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0298(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       HoverAnim;                                         // 0x02A0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 BackArrowBg;                                       // 0x02A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackArrowImage;                                    // 0x02B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                BackButton;                                        // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         BackButtonMode;                                    // 0x02C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UButton*                                BackgroundBackButton;                              // 0x02C8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 BackImage;                                         // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         CloseButtonMode;                                   // 0x02D8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ForwardArrowBg;                                    // 0x02E0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ForwardArrowImage;                                 // 0x02E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         ForwardButtonMode;                                 // 0x02F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_405;                                         // 0x02F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           KeybindClose;                                      // 0x0300(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               KeyBindContainer;                                  // 0x0308(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               KeyBindContainer_1;                                // 0x0310(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             KeybindTextBack;                                   // 0x0318(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UTextBlock*                             KeybindTextForward;                                // 0x0320(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UMenuAnchor*                            MenuAnchor_126;                                    // 0x0328(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_0;                                  // 0x0330(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnBackRequested;                                   // 0x0338(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	bool                                          ListenToEscapeKey;                                 // 0x0348(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_349[0x7];                                      // 0x0349(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UAkAudioEvent*                          AUD_Hovered;                                       // 0x0350(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          AUD_Unhovered;                                     // 0x0358(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          AUD_Click;                                         // 0x0360(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ShowKeybind;                                       // 0x0368(0x0001)(Edit, BlueprintVisible, BlueprintReadOnly, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	ESharedBackButtonTypes                        ButtonType;                                        // 0x0369(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_SharedBackButton(int32 EntryPoint);
	void OnSynchronizeProperties();
	void BndEvt__BackgroundBackButton_K2Node_ComponentBoundEvent_7_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BackgroundBackButton_K2Node_ComponentBoundEvent_6_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BackgroundBackButton_K2Node_ComponentBoundEvent_4_OnButtonClickedEvent__DelegateSignature();
	void BndEvt__BackButton_K2Node_ComponentBoundEvent_2_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BackButton_K2Node_ComponentBoundEvent_1_OnButtonHoverEvent__DelegateSignature();
	void BndEvt__BackButton_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature();
	void Tick(const struct FGeometry& MyGeometry, float InDeltaTime);
	class UWidget* OnGetMenuContent_0();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SharedBackButton_C">();
	}
	static class USharedBackButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USharedBackButton_C>();
	}
};
static_assert(alignof(USharedBackButton_C) == 0x000008, "Wrong alignment on USharedBackButton_C");
static_assert(sizeof(USharedBackButton_C) == 0x000370, "Wrong size on USharedBackButton_C");
static_assert(offsetof(USharedBackButton_C, UberGraphFrame) == 0x000298, "Member 'USharedBackButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, HoverAnim) == 0x0002A0, "Member 'USharedBackButton_C::HoverAnim' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, BackArrowBg) == 0x0002A8, "Member 'USharedBackButton_C::BackArrowBg' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, BackArrowImage) == 0x0002B0, "Member 'USharedBackButton_C::BackArrowImage' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, BackButton) == 0x0002B8, "Member 'USharedBackButton_C::BackButton' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, BackButtonMode) == 0x0002C0, "Member 'USharedBackButton_C::BackButtonMode' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, BackgroundBackButton) == 0x0002C8, "Member 'USharedBackButton_C::BackgroundBackButton' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, BackImage) == 0x0002D0, "Member 'USharedBackButton_C::BackImage' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, CloseButtonMode) == 0x0002D8, "Member 'USharedBackButton_C::CloseButtonMode' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, ForwardArrowBg) == 0x0002E0, "Member 'USharedBackButton_C::ForwardArrowBg' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, ForwardArrowImage) == 0x0002E8, "Member 'USharedBackButton_C::ForwardArrowImage' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, ForwardButtonMode) == 0x0002F0, "Member 'USharedBackButton_C::ForwardButtonMode' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, Image_405) == 0x0002F8, "Member 'USharedBackButton_C::Image_405' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, KeybindClose) == 0x000300, "Member 'USharedBackButton_C::KeybindClose' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, KeyBindContainer) == 0x000308, "Member 'USharedBackButton_C::KeyBindContainer' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, KeyBindContainer_1) == 0x000310, "Member 'USharedBackButton_C::KeyBindContainer_1' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, KeybindTextBack) == 0x000318, "Member 'USharedBackButton_C::KeybindTextBack' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, KeybindTextForward) == 0x000320, "Member 'USharedBackButton_C::KeybindTextForward' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, MenuAnchor_126) == 0x000328, "Member 'USharedBackButton_C::MenuAnchor_126' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, WidgetSwitcher_0) == 0x000330, "Member 'USharedBackButton_C::WidgetSwitcher_0' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, OnBackRequested) == 0x000338, "Member 'USharedBackButton_C::OnBackRequested' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, ListenToEscapeKey) == 0x000348, "Member 'USharedBackButton_C::ListenToEscapeKey' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, AUD_Hovered) == 0x000350, "Member 'USharedBackButton_C::AUD_Hovered' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, AUD_Unhovered) == 0x000358, "Member 'USharedBackButton_C::AUD_Unhovered' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, AUD_Click) == 0x000360, "Member 'USharedBackButton_C::AUD_Click' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, ShowKeybind) == 0x000368, "Member 'USharedBackButton_C::ShowKeybind' has a wrong offset!");
static_assert(offsetof(USharedBackButton_C, ButtonType) == 0x000369, "Member 'USharedBackButton_C::ButtonType' has a wrong offset!");

}

