#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SharedSecondaryButtonText

#include "Basic.hpp"

#include "SharedSecondaryButtonText_classes.hpp"
#include "SharedSecondaryButtonText_parameters.hpp"


namespace SDK
{

// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.ExecuteUbergraph_SharedSecondaryButtonText
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void USharedSecondaryButtonText_C::ExecuteUbergraph_SharedSecondaryButtonText(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_SharedSecondaryButtonText");

	Params::SharedSecondaryButtonText_C_ExecuteUbergraph_SharedSecondaryButtonText Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USharedSecondaryButtonText_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PreConstruct");

	Params::SharedSecondaryButtonText_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USharedSecondaryButtonText_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMouseLeave");

	Params::SharedSecondaryButtonText_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// struct FPointerEvent                    MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void USharedSecondaryButtonText_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnMouseEnter");

	Params::SharedSecondaryButtonText_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USharedSecondaryButtonText_C::BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_4_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature
// (BlueprintEvent)

void USharedSecondaryButtonText_C::BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_3_OnButtonHoverEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature
// (BlueprintEvent)

void USharedSecondaryButtonText_C::BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_2_OnButtonReleasedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature
// (BlueprintEvent)

void USharedSecondaryButtonText_C::BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_1_OnButtonPressedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature
// (BlueprintEvent)

void USharedSecondaryButtonText_C::BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("BndEvt__TelemetryButton_0_K2Node_ComponentBoundEvent_0_OnButtonClickedEvent__DelegateSignature");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.OnSynchronizeProperties
// (Event, Public, BlueprintEvent)

void USharedSecondaryButtonText_C::OnSynchronizeProperties()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("OnSynchronizeProperties");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void USharedSecondaryButtonText_C::Construct()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.UpdateButtonText
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             ButtonText_0                                           (BlueprintVisible, BlueprintReadOnly, Parm)

void USharedSecondaryButtonText_C::UpdateButtonText(const class FText& ButtonText_0)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateButtonText");

	Params::SharedSecondaryButtonText_C_UpdateButtonText Parms{};

	Parms.ButtonText_0 = std::move(ButtonText_0);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.SetButtonEnabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsEnabled                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USharedSecondaryButtonText_C::SetButtonEnabled(bool IsEnabled)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetButtonEnabled");

	Params::SharedSecondaryButtonText_C_SetButtonEnabled Parms{};

	Parms.IsEnabled = IsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.SetImage
// (Public, BlueprintCallable, BlueprintEvent)

void USharedSecondaryButtonText_C::SetImage()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetImage");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.SetIsEnabledOverride
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    InIsEnabled                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USharedSecondaryButtonText_C::SetIsEnabledOverride(bool InIsEnabled)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetIsEnabledOverride");

	Params::SharedSecondaryButtonText_C_SetIsEnabledOverride Parms{};

	Parms.InIsEnabled = InIsEnabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.StopAllAnimationsBlueprint
// (Public, BlueprintCallable, BlueprintEvent)

void USharedSecondaryButtonText_C::StopAllAnimationsBlueprint()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("StopAllAnimationsBlueprint");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.UpdateAnimation
// (Public, BlueprintCallable, BlueprintEvent)

void USharedSecondaryButtonText_C::UpdateAnimation()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateAnimation");

	UObject::ProcessEvent(Func, nullptr);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.SetButtonSelected
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsSelected                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor)

void USharedSecondaryButtonText_C::SetButtonSelected(bool IsSelected)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetButtonSelected");

	Params::SharedSecondaryButtonText_C_SetButtonSelected Parms{};

	Parms.IsSelected = IsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.On_TooltipAnchor_GetMenuContent_0
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* USharedSecondaryButtonText_C::On_TooltipAnchor_GetMenuContent_0()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("On_TooltipAnchor_GetMenuContent_0");

	Params::SharedSecondaryButtonText_C_On_TooltipAnchor_GetMenuContent_0 Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.SetActionTarget
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FString                           Target                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void USharedSecondaryButtonText_C::SetActionTarget(const class FString& Target)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetActionTarget");

	Params::SharedSecondaryButtonText_C_SetActionTarget Parms{};

	Parms.Target = std::move(Target);

	UObject::ProcessEvent(Func, &Parms);
}


// Function SharedSecondaryButtonText.SharedSecondaryButtonText_C.SetButtonTooltip
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class FText                             NewTooltip                                             (BlueprintVisible, BlueprintReadOnly, Parm)

void USharedSecondaryButtonText_C::SetButtonTooltip(const class FText& NewTooltip)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetButtonTooltip");

	Params::SharedSecondaryButtonText_C_SetButtonTooltip Parms{};

	Parms.NewTooltip = std::move(NewTooltip);

	UObject::ProcessEvent(Func, &Parms);
}

}

