#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SharedButtonStyle

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"


namespace SDK
{

// UserDefinedStruct SharedButtonStyle.SharedButtonStyle
// 0x0048 (0x0048 - 0x0000)
struct FSharedButtonStyle final
{
public:
	struct FLinearColor                           BackgroundColor_2_BA973BC94AC9F8AC252C34BD4450263B; // 0x0000(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           LabelColor_4_A03B98D948AA7759CB4B2DA7A90661D1;     // 0x0010(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FLinearColor                           DisabledBackgroundColor_6_EB50AD2C4852D11D853BB5A0BCE0D454; // 0x0020(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          AUD_Click_12_C86DC8EB425EED425BC55ABD5D69C9DC;     // 0x0030(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          AUD_HoverA_14_2DF682924FCF9618E1819D8466EE64D6;    // 0x0038(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAkAudioEvent*                          AUD_HoverB_15_2ADB07144A84ED2B256F52AA3412E93F;    // 0x0040(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FSharedButtonStyle) == 0x000008, "Wrong alignment on FSharedButtonStyle");
static_assert(sizeof(FSharedButtonStyle) == 0x000048, "Wrong size on FSharedButtonStyle");
static_assert(offsetof(FSharedButtonStyle, BackgroundColor_2_BA973BC94AC9F8AC252C34BD4450263B) == 0x000000, "Member 'FSharedButtonStyle::BackgroundColor_2_BA973BC94AC9F8AC252C34BD4450263B' has a wrong offset!");
static_assert(offsetof(FSharedButtonStyle, LabelColor_4_A03B98D948AA7759CB4B2DA7A90661D1) == 0x000010, "Member 'FSharedButtonStyle::LabelColor_4_A03B98D948AA7759CB4B2DA7A90661D1' has a wrong offset!");
static_assert(offsetof(FSharedButtonStyle, DisabledBackgroundColor_6_EB50AD2C4852D11D853BB5A0BCE0D454) == 0x000020, "Member 'FSharedButtonStyle::DisabledBackgroundColor_6_EB50AD2C4852D11D853BB5A0BCE0D454' has a wrong offset!");
static_assert(offsetof(FSharedButtonStyle, AUD_Click_12_C86DC8EB425EED425BC55ABD5D69C9DC) == 0x000030, "Member 'FSharedButtonStyle::AUD_Click_12_C86DC8EB425EED425BC55ABD5D69C9DC' has a wrong offset!");
static_assert(offsetof(FSharedButtonStyle, AUD_HoverA_14_2DF682924FCF9618E1819D8466EE64D6) == 0x000038, "Member 'FSharedButtonStyle::AUD_HoverA_14_2DF682924FCF9618E1819D8466EE64D6' has a wrong offset!");
static_assert(offsetof(FSharedButtonStyle, AUD_HoverB_15_2ADB07144A84ED2B256F52AA3412E93F) == 0x000040, "Member 'FSharedButtonStyle::AUD_HoverB_15_2ADB07144A84ED2B256F52AA3412E93F' has a wrong offset!");

}

