#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShooterCharacterAudioAttenuationComponent

#include "Basic.hpp"

#include "ShooterCharacterAudioAttenuationComponent_classes.hpp"
#include "ShooterCharacterAudioAttenuationComponent_parameters.hpp"


namespace SDK
{

// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.ExecuteUbergraph_ShooterCharacterAudioAttenuationComponent
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShooterCharacterAudioAttenuationComponent_C::ExecuteUbergraph_ShooterCharacterAudioAttenuationComponent(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_ShooterCharacterAudioAttenuationComponent");

	Params::ShooterCharacterAudioAttenuationComponent_C_ExecuteUbergraph_ShooterCharacterAudioAttenuationComponent Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.ClearCurrentOneShotVisualization
// (BlueprintCallable, BlueprintEvent)

void UShooterCharacterAudioAttenuationComponent_C::ClearCurrentOneShotVisualization()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ClearCurrentOneShotVisualization");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.ReceiveBeginPlay
// (Event, Public, BlueprintEvent)

void UShooterCharacterAudioAttenuationComponent_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.AddNewAttenuationVisual
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAkComponent*                     AkComponent                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OwningActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   Radius_0                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// Enum_AttenuationVisualization           Type                                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShooterCharacterAudioAttenuationComponent_C::AddNewAttenuationVisual(class UAkComponent* AkComponent, class AActor* OwningActor, float Radius_0, Enum_AttenuationVisualization Type)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("AddNewAttenuationVisual");

	Params::ShooterCharacterAudioAttenuationComponent_C_AddNewAttenuationVisual Parms{};

	Parms.AkComponent = AkComponent;
	Parms.OwningActor = OwningActor;
	Parms.Radius_0 = Radius_0;
	Parms.Type = Type;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.RemoveAttenuationVisual
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UAkComponent*                     AkComponent                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           Actor                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UShooterCharacterAudioAttenuationComponent_C::RemoveAttenuationVisual(class UAkComponent* AkComponent, class AActor* Actor)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("RemoveAttenuationVisual");

	Params::ShooterCharacterAudioAttenuationComponent_C_RemoveAttenuationVisual Parms{};

	Parms.AkComponent = AkComponent;
	Parms.Actor = Actor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.GetActiveWidgets
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// TArray<class UUserWidget*>              Values                                                 (Parm, OutParm, ZeroConstructor, ContainsInstancedReference)

void UShooterCharacterAudioAttenuationComponent_C::GetActiveWidgets(TArray<class UUserWidget*>* Values)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("GetActiveWidgets");

	Params::ShooterCharacterAudioAttenuationComponent_C_GetActiveWidgets Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Values != nullptr)
		*Values = std::move(Parms.Values);
}


// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.UpdateVisualizations
// (Public, BlueprintCallable, BlueprintEvent)

void UShooterCharacterAudioAttenuationComponent_C::UpdateVisualizations()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("UpdateVisualizations");

	UObject::ProcessEvent(Func, nullptr);
}


// Function ShooterCharacterAudioAttenuationComponent.ShooterCharacterAudioAttenuationComponent_C.PruneConstantArray
// (Public, BlueprintCallable, BlueprintEvent)

void UShooterCharacterAudioAttenuationComponent_C::PruneConstantArray()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("PruneConstantArray");

	UObject::ProcessEvent(Func, nullptr);
}

}

