#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SprayActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SprayActionTraits.SprayActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class USprayActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SprayActionTraits_C">();
	}
	static class USprayActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USprayActionTraits_C>();
	}
};
static_assert(alignof(USprayActionTraits_C) == 0x000008, "Wrong alignment on USprayActionTraits_C");
static_assert(sizeof(USprayActionTraits_C) == 0x000040, "Wrong size on USprayActionTraits_C");

}

