#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_AttenuationInformation

#include "Basic.hpp"

#include "Enum_AttenuationVisualization_structs.hpp"


namespace SDK
{

// UserDefinedStruct Struct_AttenuationInformation.Struct_AttenuationInformation
// 0x0018 (0x0018 - 0x0000)
struct FStruct_AttenuationInformation final
{
public:
	class UAkComponent*                           AkComponent_14_106F310C43CDB01FD0A8DEBFDE517218;   // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AActor*                                 OwningActor_17_C26E53BD408A01E63122CDB78028F7CC;   // 0x0008(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Radius_5_E6DBEEBE41FF7D345D977287C3DB0054;         // 0x0010(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	Enum_AttenuationVisualization                 Type_12_5BA7C0944FAC16BF24CA378849F7DB22;          // 0x0014(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(FStruct_AttenuationInformation) == 0x000008, "Wrong alignment on FStruct_AttenuationInformation");
static_assert(sizeof(FStruct_AttenuationInformation) == 0x000018, "Wrong size on FStruct_AttenuationInformation");
static_assert(offsetof(FStruct_AttenuationInformation, AkComponent_14_106F310C43CDB01FD0A8DEBFDE517218) == 0x000000, "Member 'FStruct_AttenuationInformation::AkComponent_14_106F310C43CDB01FD0A8DEBFDE517218' has a wrong offset!");
static_assert(offsetof(FStruct_AttenuationInformation, OwningActor_17_C26E53BD408A01E63122CDB78028F7CC) == 0x000008, "Member 'FStruct_AttenuationInformation::OwningActor_17_C26E53BD408A01E63122CDB78028F7CC' has a wrong offset!");
static_assert(offsetof(FStruct_AttenuationInformation, Radius_5_E6DBEEBE41FF7D345D977287C3DB0054) == 0x000010, "Member 'FStruct_AttenuationInformation::Radius_5_E6DBEEBE41FF7D345D977287C3DB0054' has a wrong offset!");
static_assert(offsetof(FStruct_AttenuationInformation, Type_12_5BA7C0944FAC16BF24CA378849F7DB22) == 0x000014, "Member 'FStruct_AttenuationInformation::Type_12_5BA7C0944FAC16BF24CA378849F7DB22' has a wrong offset!");

}

