#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SwapPrimarySecondaryActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass SwapPrimarySecondaryActionTraits.SwapPrimarySecondaryActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class USwapPrimarySecondaryActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SwapPrimarySecondaryActionTraits_C">();
	}
	static class USwapPrimarySecondaryActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USwapPrimarySecondaryActionTraits_C>();
	}
};
static_assert(alignof(USwapPrimarySecondaryActionTraits_C) == 0x000008, "Wrong alignment on USwapPrimarySecondaryActionTraits_C");
static_assert(sizeof(USwapPrimarySecondaryActionTraits_C) == 0x000040, "Wrong size on USwapPrimarySecondaryActionTraits_C");

}

