#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TapHoldWeaponSwapActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TapHoldWeaponSwapActionTraits.TapHoldWeaponSwapActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UTapHoldWeaponSwapActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TapHoldWeaponSwapActionTraits_C">();
	}
	static class UTapHoldWeaponSwapActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTapHoldWeaponSwapActionTraits_C>();
	}
};
static_assert(alignof(UTapHoldWeaponSwapActionTraits_C) == 0x000008, "Wrong alignment on UTapHoldWeaponSwapActionTraits_C");
static_assert(sizeof(UTapHoldWeaponSwapActionTraits_C) == 0x000040, "Wrong size on UTapHoldWeaponSwapActionTraits_C");

}

