#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TapHoldDropItemsActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TapHoldDropItemsActionTraits.TapHoldDropItemsActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UTapHoldDropItemsActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TapHoldDropItemsActionTraits_C">();
	}
	static class UTapHoldDropItemsActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTapHoldDropItemsActionTraits_C>();
	}
};
static_assert(alignof(UTapHoldDropItemsActionTraits_C) == 0x000008, "Wrong alignment on UTapHoldDropItemsActionTraits_C");
static_assert(sizeof(UTapHoldDropItemsActionTraits_C) == 0x000040, "Wrong size on UTapHoldDropItemsActionTraits_C");

}

