#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ToggleSightLinesActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ToggleSightLinesActionTraits.ToggleSightLinesActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UToggleSightLinesActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ToggleSightLinesActionTraits_C">();
	}
	static class UToggleSightLinesActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UToggleSightLinesActionTraits_C>();
	}
};
static_assert(alignof(UToggleSightLinesActionTraits_C) == 0x000008, "Wrong alignment on UToggleSightLinesActionTraits_C");
static_assert(sizeof(UToggleSightLinesActionTraits_C) == 0x000040, "Wrong size on UToggleSightLinesActionTraits_C");

}

