#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ToggleFreeCamActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ToggleFreeCamActionTraits.ToggleFreeCamActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UToggleFreeCamActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ToggleFreeCamActionTraits_C">();
	}
	static class UToggleFreeCamActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UToggleFreeCamActionTraits_C>();
	}
};
static_assert(alignof(UToggleFreeCamActionTraits_C) == 0x000008, "Wrong alignment on UToggleFreeCamActionTraits_C");
static_assert(sizeof(UToggleFreeCamActionTraits_C) == 0x000040, "Wrong size on UToggleFreeCamActionTraits_C");

}

