#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TransitionManagerWidgetBP

#include "Basic.hpp"

#include "TransitionManagerWidgetBP_classes.hpp"
#include "TransitionManagerWidgetBP_parameters.hpp"


namespace SDK
{

// Function TransitionManagerWidgetBP.TransitionManagerWidgetBP_C.ExecuteUbergraph_TransitionManagerWidgetBP
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTransitionManagerWidgetBP_C::ExecuteUbergraph_TransitionManagerWidgetBP(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("ExecuteUbergraph_TransitionManagerWidgetBP");

	Params::TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransitionManagerWidgetBP.TransitionManagerWidgetBP_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// struct FGeometry                        MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTransitionManagerWidgetBP_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("Tick");

	Params::TransitionManagerWidgetBP_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function TransitionManagerWidgetBP.TransitionManagerWidgetBP_C.HandleWidgetAddedToContainerWidget
// (Event, Public, BlueprintEvent)
// Parameters:
// class USimpleLifecycleWidget*           TransitionWidget                                       (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPanelSlot*                       LayoutSlot                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UTransitionManagerWidgetBP_C::HandleWidgetAddedToContainerWidget(class USimpleLifecycleWidget* TransitionWidget, class UPanelSlot* LayoutSlot)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("HandleWidgetAddedToContainerWidget");

	Params::TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget Parms{};

	Parms.TransitionWidget = TransitionWidget;
	Parms.LayoutSlot = LayoutSlot;

	UObject::ProcessEvent(Func, &Parms);
}

}

