#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TransitionManagerWidgetBP

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "CoreUObject_structs.hpp"


namespace SDK::Params
{

// Function TransitionManagerWidgetBP.TransitionManagerWidgetBP_C.ExecuteUbergraph_TransitionManagerWidgetBP
// 0x00D0 (0x00D0 - 0x0000)
struct TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FMargin                                K2Node_MakeStruct_Margin;                          // 0x0004(0x0010)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_14[0x4];                                       // 0x0014(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class USimpleLifecycleWidget*                 K2Node_Event_TransitionWidget;                     // 0x0018(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             K2Node_Event_LayoutSlot;                           // 0x0020(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UOverlaySlot*                           K2Node_DynamicCast_AsOverlay_Slot;                 // 0x0028(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0030(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_31[0x3];                                       // 0x0031(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGeometry                              K2Node_Event_MyGeometry;                           // 0x0034(0x0038)(IsPlainOldData, NoDestructor)
	float                                         K2Node_Event_InDeltaTime;                          // 0x006C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetLocalSize_ReturnValue;                 // 0x0070(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetLocalSize_ReturnValue_1;               // 0x0078(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X;                          // 0x0080(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y;                          // 0x0084(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_1;                        // 0x0088(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_1;                        // 0x008C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_GetLocalSize_ReturnValue_2;               // 0x0090(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue;            // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_X_2;                        // 0x009C(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_BreakVector2D_Y_2;                        // 0x00A0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue;          // 0x00A4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_1;          // 0x00A8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_2;          // 0x00AC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue;                 // 0x00B0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_Greater_FloatFloat_ReturnValue;           // 0x00B8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_B9[0x3];                                       // 0x00B9(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	float                                         CallFunc_Multiply_FloatFloat_ReturnValue;          // 0x00BC(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Subtract_FloatFloat_ReturnValue_1;        // 0x00C0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CallFunc_Divide_FloatFloat_ReturnValue_3;          // 0x00C4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector2D                              CallFunc_MakeVector2D_ReturnValue_1;               // 0x00C8(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP) == 0x000008, "Wrong alignment on TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP");
static_assert(sizeof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP) == 0x0000D0, "Wrong size on TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, EntryPoint) == 0x000000, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::EntryPoint' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, K2Node_MakeStruct_Margin) == 0x000004, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::K2Node_MakeStruct_Margin' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, K2Node_Event_TransitionWidget) == 0x000018, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::K2Node_Event_TransitionWidget' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, K2Node_Event_LayoutSlot) == 0x000020, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::K2Node_Event_LayoutSlot' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, K2Node_DynamicCast_AsOverlay_Slot) == 0x000028, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::K2Node_DynamicCast_AsOverlay_Slot' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, K2Node_DynamicCast_bSuccess) == 0x000030, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, K2Node_Event_MyGeometry) == 0x000034, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::K2Node_Event_MyGeometry' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, K2Node_Event_InDeltaTime) == 0x00006C, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::K2Node_Event_InDeltaTime' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_GetLocalSize_ReturnValue) == 0x000070, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_GetLocalSize_ReturnValue' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_GetLocalSize_ReturnValue_1) == 0x000078, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_GetLocalSize_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_BreakVector2D_X) == 0x000080, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_BreakVector2D_X' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_BreakVector2D_Y) == 0x000084, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_BreakVector2D_Y' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_BreakVector2D_X_1) == 0x000088, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_BreakVector2D_X_1' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_BreakVector2D_Y_1) == 0x00008C, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_BreakVector2D_Y_1' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_GetLocalSize_ReturnValue_2) == 0x000090, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_GetLocalSize_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Divide_FloatFloat_ReturnValue) == 0x000098, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Divide_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_BreakVector2D_X_2) == 0x00009C, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_BreakVector2D_X_2' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_BreakVector2D_Y_2) == 0x0000A0, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_BreakVector2D_Y_2' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Subtract_FloatFloat_ReturnValue) == 0x0000A4, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Subtract_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Divide_FloatFloat_ReturnValue_1) == 0x0000A8, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Divide_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Divide_FloatFloat_ReturnValue_2) == 0x0000AC, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Divide_FloatFloat_ReturnValue_2' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_MakeVector2D_ReturnValue) == 0x0000B0, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_MakeVector2D_ReturnValue' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Greater_FloatFloat_ReturnValue) == 0x0000B8, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Greater_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Multiply_FloatFloat_ReturnValue) == 0x0000BC, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Multiply_FloatFloat_ReturnValue' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Subtract_FloatFloat_ReturnValue_1) == 0x0000C0, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Subtract_FloatFloat_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_Divide_FloatFloat_ReturnValue_3) == 0x0000C4, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_Divide_FloatFloat_ReturnValue_3' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP, CallFunc_MakeVector2D_ReturnValue_1) == 0x0000C8, "Member 'TransitionManagerWidgetBP_C_ExecuteUbergraph_TransitionManagerWidgetBP::CallFunc_MakeVector2D_ReturnValue_1' has a wrong offset!");

// Function TransitionManagerWidgetBP.TransitionManagerWidgetBP_C.Tick
// 0x003C (0x003C - 0x0000)
struct TransitionManagerWidgetBP_C_Tick final
{
public:
	struct FGeometry                              MyGeometry;                                        // 0x0000(0x0038)(BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
	float                                         InDeltaTime;                                       // 0x0038(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(TransitionManagerWidgetBP_C_Tick) == 0x000004, "Wrong alignment on TransitionManagerWidgetBP_C_Tick");
static_assert(sizeof(TransitionManagerWidgetBP_C_Tick) == 0x00003C, "Wrong size on TransitionManagerWidgetBP_C_Tick");
static_assert(offsetof(TransitionManagerWidgetBP_C_Tick, MyGeometry) == 0x000000, "Member 'TransitionManagerWidgetBP_C_Tick::MyGeometry' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_Tick, InDeltaTime) == 0x000038, "Member 'TransitionManagerWidgetBP_C_Tick::InDeltaTime' has a wrong offset!");

// Function TransitionManagerWidgetBP.TransitionManagerWidgetBP_C.HandleWidgetAddedToContainerWidget
// 0x0010 (0x0010 - 0x0000)
struct TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget final
{
public:
	class USimpleLifecycleWidget*                 TransitionWidget;                                  // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UPanelSlot*                             LayoutSlot;                                        // 0x0008(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget) == 0x000008, "Wrong alignment on TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget");
static_assert(sizeof(TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget) == 0x000010, "Wrong size on TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget");
static_assert(offsetof(TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget, TransitionWidget) == 0x000000, "Member 'TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget::TransitionWidget' has a wrong offset!");
static_assert(offsetof(TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget, LayoutSlot) == 0x000008, "Member 'TransitionManagerWidgetBP_C_HandleWidgetAddedToContainerWidget::LayoutSlot' has a wrong offset!");

}

