#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UmbraCulling

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// Class UmbraCulling.UmbraPrecomputedData
// 0x0010 (0x0040 - 0x0030)
class UUmbraPrecomputedData final : public UAssetUserData
{
public:
	TArray<uint32>                                Data;                                              // 0x0030(0x0010)(ZeroConstructor, NativeAccessSpecifierPublic)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"UmbraPrecomputedData">();
	}
	static class UUmbraPrecomputedData* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUmbraPrecomputedData>();
	}
};
static_assert(alignof(UUmbraPrecomputedData) == 0x000008, "Wrong alignment on UUmbraPrecomputedData");
static_assert(sizeof(UUmbraPrecomputedData) == 0x000040, "Wrong size on UUmbraPrecomputedData");
static_assert(offsetof(UUmbraPrecomputedData, Data) == 0x000030, "Member 'UUmbraPrecomputedData::Data' has a wrong offset!");

}

