#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UseObjectActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass UseObjectActionTraits.UseObjectActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UUseObjectActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"UseObjectActionTraits_C">();
	}
	static class UUseObjectActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UUseObjectActionTraits_C>();
	}
};
static_assert(alignof(UUseObjectActionTraits_C) == 0x000008, "Wrong alignment on UUseObjectActionTraits_C");
static_assert(sizeof(UUseObjectActionTraits_C) == 0x000040, "Wrong size on UUseObjectActionTraits_C");

}

