#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VOEmoteCommendActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VOEmoteCommendActionTraits.VOEmoteCommendActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UVOEmoteCommendActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VOEmoteCommendActionTraits_C">();
	}
	static class UVOEmoteCommendActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVOEmoteCommendActionTraits_C>();
	}
};
static_assert(alignof(UVOEmoteCommendActionTraits_C) == 0x000008, "Wrong alignment on UVOEmoteCommendActionTraits_C");
static_assert(sizeof(UVOEmoteCommendActionTraits_C) == 0x000040, "Wrong size on UVOEmoteCommendActionTraits_C");

}

