#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VOEmoteSorryActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VOEmoteSorryActionTraits.VOEmoteSorryActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UVOEmoteSorryActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VOEmoteSorryActionTraits_C">();
	}
	static class UVOEmoteSorryActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVOEmoteSorryActionTraits_C>();
	}
};
static_assert(alignof(UVOEmoteSorryActionTraits_C) == 0x000008, "Wrong alignment on UVOEmoteSorryActionTraits_C");
static_assert(sizeof(UVOEmoteSorryActionTraits_C) == 0x000040, "Wrong size on UVOEmoteSorryActionTraits_C");

}

