#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VOEmoteThanksActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass VOEmoteThanksActionTraits.VOEmoteThanksActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UVOEmoteThanksActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"VOEmoteThanksActionTraits_C">();
	}
	static class UVOEmoteThanksActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVOEmoteThanksActionTraits_C>();
	}
};
static_assert(alignof(UVOEmoteThanksActionTraits_C) == 0x000008, "Wrong alignment on UVOEmoteThanksActionTraits_C");
static_assert(sizeof(UVOEmoteThanksActionTraits_C) == 0x000040, "Wrong size on UVOEmoteThanksActionTraits_C");

}

