#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WallPen_VeryLow

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WallPen_VeryLow.WallPen_VeryLow_C
// 0x0000 (0x0048 - 0x0048)
class UWallPen_VeryLow_C final : public UAresWallPenetration
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WallPen_VeryLow_C">();
	}
	static class UWallPen_VeryLow_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWallPen_VeryLow_C>();
	}
};
static_assert(alignof(UWallPen_VeryLow_C) == 0x000008, "Wrong alignment on UWallPen_VeryLow_C");
static_assert(sizeof(UWallPen_VeryLow_C) == 0x000048, "Wrong size on UWallPen_VeryLow_C");

}

