#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WallPen_VeryHigh

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WallPen_VeryHigh.WallPen_VeryHigh_C
// 0x0000 (0x0048 - 0x0048)
class UWallPen_VeryHigh_C final : public UAresWallPenetration
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WallPen_VeryHigh_C">();
	}
	static class UWallPen_VeryHigh_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWallPen_VeryHigh_C>();
	}
};
static_assert(alignof(UWallPen_VeryHigh_C) == 0x000008, "Wrong alignment on UWallPen_VeryHigh_C");
static_assert(sizeof(UWallPen_VeryHigh_C) == 0x000048, "Wrong size on UWallPen_VeryHigh_C");

}

