#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WhisperChatActionTraits

#include "Basic.hpp"

#include "ShooterGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WhisperChatActionTraits.WhisperChatActionTraits_C
// 0x0000 (0x0040 - 0x0040)
class UWhisperChatActionTraits_C final : public UActionTraits
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WhisperChatActionTraits_C">();
	}
	static class UWhisperChatActionTraits_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWhisperChatActionTraits_C>();
	}
};
static_assert(alignof(UWhisperChatActionTraits_C) == 0x000008, "Wrong alignment on UWhisperChatActionTraits_C");
static_assert(sizeof(UWhisperChatActionTraits_C) == 0x000040, "Wrong size on UWhisperChatActionTraits_C");

}

